{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Nacional\",\"Medidas\",\"Incidencias\",\"FechasIncidencias\",\"NPS_NACIONAL\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"NPS_XB\",\"NPS_PHAR\",\"NPS_BBA\",\"NPS_VMODAL\",\"Parameter2\",\"Transform Sample File (2)\",\"Sample File (2)\",\"Transform File (2)\",\"CATEGORIAS\",\"Medidas NPS\",\"Clasificación NPS\",\"Sector\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "es-MX",
    "cultures": [
      {
        "name": "es-MX",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "470329e7-9932-46ce-88fb-4fb58286dfb6",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    NPS_NAL_Table = Source{[Item=\"NPS_NAL\",Kind=\"Table\"]}[Data]",
          "in",
          "    NPS_NAL_Table"
        ],
        "kind": "m",
        "lineageTag": "51f720f7-aae5-4193-8747-83d611aabb0b",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "5e2c5af9-dff2-4804-b097-d59b9fa07878",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    NPS_NAL_Table = Source{[Item=\"NPS_NAL\",Kind=\"Table\"]}[Data]",
          "in",
          "    NPS_NAL_Table",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "8c9f4519-976e-4058-b9d3-68b971bfd759",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1\\Helper Queries"
      },
      {
        "name": "Parameter2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "2ceccdd2-fe9f-48fc-b379-0e7ae53a36e9",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1 (2)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter2, null, true),",
          "    NPS_XB_Table = Source{[Item=\"NPS_XB\",Kind=\"Table\"]}[Data]",
          "in",
          "    NPS_XB_Table"
        ],
        "kind": "m",
        "lineageTag": "184b5303-b480-4808-be6a-7825f2593c1a",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1 (2)"
      },
      {
        "name": "Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "aed73583-0783-436e-adfe-1603960136d6",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1 (2)\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "    Source = Excel.Workbook(Parameter2, null, true),",
          "    NPS_XB_Table = Source{[Item=\"NPS_XB\",Kind=\"Table\"]}[Data]",
          "in",
          "    NPS_XB_Table",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "ef108edb-3ef8-4080-9553-46c60ba49259",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (2)\"\"}\" ]",
        "queryGroup": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1 (2)\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "BDcarriercare"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Incidencias Carrier Care"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1 (2)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "BDcarriercare\\Transform File from MASTER VISITA CARRIERS Q1 (2)\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "8"
          }
        ],
        "folder": "NPS"
      }
    ],
    "relationships": [
      {
        "name": "6ac4a728-6f41-407f-a0b4-535d0d1e6815",
        "fromColumn": "FECHA DE SOLICITUD",
        "fromTable": "Nacional",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_41d2e0e5-9585-4858-915c-164254b125a7"
      },
      {
        "name": "db47e2cf-aedf-4ce1-bde5-b2b15a85a371",
        "fromColumn": "Date",
        "fromTable": "Calendario",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f70aa27b-5a03-432c-a48a-7e9b1c762409"
      },
      {
        "name": "329662f2-ee5a-4e29-aa3c-933e7957d79a",
        "fromColumn": "FECHA DE RECEPCIÓN",
        "fromTable": "Incidencias",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ee042d8e-6b6a-4c95-a023-0597a13a14e7"
      },
      {
        "name": "505be358-7b77-43bf-a5bb-446a1c6580eb",
        "fromColumn": "FECHA DE ASIGNACIÓN",
        "fromTable": "Incidencias",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_995a9f87-863d-49c7-8a02-e1834cd06213"
      },
      {
        "name": "c3854045-0228-4ff8-a0b4-9cd3515e9617",
        "fromColumn": "FECHA DE CIERRE",
        "fromTable": "Incidencias",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_fca9d86d-6923-4da5-bbeb-e5ade30b71dc"
      },
      {
        "name": "caebeb6b-a2e2-45b8-b9d3-1d4b9f1e461f",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "FOLIO PQR",
        "fromTable": "FechasIncidencias",
        "toColumn": "FOLIO PQR",
        "toTable": "Incidencias"
      },
      {
        "name": "a1b65d05-e011-4e3d-8490-4917cea5c8bb",
        "fromColumn": "FECHA",
        "fromTable": "NPS_XB",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_57bd1f4e-d41f-4c3e-bf40-4b347aeaa27e"
      },
      {
        "name": "597c686b-f382-4b30-9e00-d1dda8a0400d",
        "fromColumn": "value1",
        "fromTable": "my bins",
        "toColumn": "BandSizeOpEx",
        "toTable": "BandSizeOpEx"
      },
      {
        "name": "16d28c27-463c-4df5-a1ae-b1133944784f",
        "fromColumn": "Date",
        "fromTable": "calendarconection",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendarconnection_Alternative"
      },
      {
        "name": "27617916-1c04-4da9-a824-b9e609aef83a",
        "fromColumn": "Min",
        "fromTable": "FechasIncidencias",
        "toColumn": "Date",
        "toTable": "calendarconection"
      },
      {
        "name": "08eb56e0-80f9-4367-b9a9-a899b039dc3f",
        "fromColumn": "FECHA",
        "fromTable": "NPS_NACIONAL",
        "toColumn": "Date",
        "toTable": "calendarconection"
      },
      {
        "name": "fa424948-e3eb-4a32-b1bb-81d1a83f5b2e",
        "fromColumn": "Date",
        "fromTable": "Calendarconnection_Alternative",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_464403aa-219d-4a77-8110-84719da5ddfb"
      },
      {
        "name": "f5510de6-f291-4c14-adef-37da8920fca0",
        "fromColumn": "FECHA",
        "fromTable": "NPS_PHAR",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_673e204d-2ac7-4cff-afd1-28ed577fd8a9"
      },
      {
        "name": "dc07c624-2029-478c-aac2-7b37a171ca5f",
        "fromColumn": "FECHA",
        "fromTable": "NPS_BBA",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_cfa88921-9f1b-4bf9-a5b6-66ab306bacbf"
      },
      {
        "name": "147e921d-aa5e-43d9-b978-d9a6c4b224f7",
        "fromColumn": "Sector",
        "fromTable": "NPS_NACIONAL",
        "toColumn": "Sector",
        "toTable": "Sector"
      },
      {
        "name": "ec946c5f-e1e3-4a4f-bcaf-56f9646b5f1e",
        "fromColumn": "FECHA",
        "fromTable": "NPS_VMODAL",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_12956af6-a2d5-4b44-b5ce-445153b830b1"
      }
    ],
    "sourceQueryCulture": "es-MX",
    "tables": [
      {
        "name": "DateTableTemplate_99f4251b-2391-4abf-9316-e95748c47f82",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7d9666cb-c96d-4b98-8223-b524ccc2cf0c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d649210c-8b94-40db-8d42-770b3e340217",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cb197f71-4f8f-40de-a1a2-8de05a4a158b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b21bf0ef-da95-4322-b9b6-0fed2b063d80",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "643ed6d0-61a6-477a-8de4-54e2a52038f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c86b6ddc-4246-4a15-a42b-01f1b369f44b",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "05e9ce94-9e80-4a4e-9273-0df915169ad3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "9d84c26a-be63-4105-b620-7af98ffe880c",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "7576dc1e-fd17-484c-a65b-cb60ef0ced39",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "683f19e3-a71e-48b7-bd9b-24c36b507367",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "1cb6a864-3514-45b0-b957-55092607faba",
                "ordinal": 3
              }
            ],
            "lineageTag": "cf62e5db-35a0-4895-947a-665818c6cc2c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9609f0cd-9295-4e12-9042-7ab4341b2111",
        "partitions": [
          {
            "name": "DateTableTemplate_99f4251b-2391-4abf-9316-e95748c47f82-d7d03ec3-f5e4-4b7b-bca4-1d6731eb9513",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Nacional",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CRM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4105fbc7-b088-40c7-a0dc-1721f9e9efd0",
            "sourceColumn": "CRM",
            "summarizeBy": "none"
          },
          {
            "name": "Prioridad",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "668b8408-dc76-4ee3-8d48-1cec5b3119f0",
            "sourceColumn": "Prioridad",
            "summarizeBy": "none"
          },
          {
            "name": "Proveedor/Nombre Comercial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1d7c747-e9b5-44dd-a565-ad632a0e3a4e",
            "sourceColumn": "Proveedor/Nombre Comercial",
            "summarizeBy": "none"
          },
          {
            "name": "Razón social",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "326c21de-113e-4f23-8833-0abf537a3b14",
            "sourceColumn": "Razón social",
            "summarizeBy": "none"
          },
          {
            "name": "Origen",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e07e4c5b-f5c3-4786-913e-8312146295b4",
            "sourceColumn": "Origen",
            "summarizeBy": "none"
          },
          {
            "name": "LINEA DE NEGOCIO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba4631e7-cbb0-4ece-9aac-2ebe3a69ba04",
            "sourceColumn": "LINEA DE NEGOCIO",
            "summarizeBy": "none"
          },
          {
            "name": "# SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a3a658e-fb08-41bd-a74f-74b68faaaf08",
            "sourceColumn": "# SAP",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA DE SOLICITUD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bb18a4c7-3331-45f5-bf9f-76a59b5f1236",
            "sourceColumn": "FECHA DE SOLICITUD",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_41d2e0e5-9585-4858-915c-164254b125a7"
                },
                "isDefault": true,
                "relationship": "6ac4a728-6f41-407f-a0b4-535d0d1e6815"
              }
            ]
          },
          {
            "name": "FECHA DE ALTA SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d852f15-d3b9-4877-9b86-1fcd639799f1",
            "sourceColumn": "FECHA DE ALTA SAP",
            "summarizeBy": "none"
          },
          {
            "name": "Acta constitutiva",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2bdb1cf-2fc0-4790-a75f-fb92bd2ab0fa",
            "sourceColumn": "Acta constitutiva",
            "summarizeBy": "none"
          },
          {
            "name": "Poder notarial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea3bccf4-7791-4912-aebe-2f38fe54ffee",
            "sourceColumn": "Poder notarial",
            "summarizeBy": "none"
          },
          {
            "name": "INE de rep legal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7037a1e-786f-4f3e-94ca-9e8d48bafed9",
            "sourceColumn": "INE de rep legal",
            "summarizeBy": "none"
          },
          {
            "name": "Constancia Situación Fiscal (RFC).",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ef6c7b8-a70b-4296-8589-6456f785c84c",
            "sourceColumn": "Constancia Situación Fiscal (RFC).",
            "summarizeBy": "none"
          },
          {
            "name": "Opinión favorable del SAT Actualizada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bb03500-70d9-4727-8b15-79a836c17ce6",
            "sourceColumn": "Opinión favorable del SAT Actualizada",
            "summarizeBy": "none"
          },
          {
            "name": "Copia de carátula de estado de cuenta (No más de 3 meses de antigüedad)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01bfc77e-c011-4c0c-84ad-8713eeb5238d",
            "sourceColumn": "Copia de carátula de estado de cuenta (No más de 3 meses de antigüedad)",
            "summarizeBy": "none"
          },
          {
            "name": "Comprobante de domicilio (no más de 3 meses de antigüedad). (OBLIGATORIO)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7163d906-8231-478b-9d0b-c19fed47ca8b",
            "sourceColumn": "Comprobante de domicilio (no más de 3 meses de antigüedad). (OBLIGATORIO)",
            "summarizeBy": "none"
          },
          {
            "name": "Permiso de la SCT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "844d0c93-c392-4f02-9559-9aa828fe4396",
            "sourceColumn": "Permiso de la SCT",
            "summarizeBy": "none"
          },
          {
            "name": "Llenado de RFI Del Transportista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d26d050b-ed4e-44ae-9690-0a2a24373b7d",
            "sourceColumn": "Llenado de RFI Del Transportista",
            "summarizeBy": "none"
          },
          {
            "name": "Alta de Proveedores",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f237a26-f4e0-4a0b-8c8c-f3b055321fd0",
            "sourceColumn": "Alta de Proveedores",
            "summarizeBy": "none"
          },
          {
            "name": "Firma y llenado de Convenio Comercial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6af507dd-6416-4049-8db8-fbebbbd6b53f",
            "sourceColumn": "Firma y llenado de Convenio Comercial",
            "summarizeBy": "none"
          },
          {
            "name": "INE de representante legal.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "801b8d5d-4b81-4f19-bc6d-073b06aca80d",
            "sourceColumn": "INE de representante legal.",
            "summarizeBy": "none"
          },
          {
            "name": "Constancia de Situación Fiscal (RFC).",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5040482-6451-4176-845f-5698ff490c42",
            "sourceColumn": "Constancia de Situación Fiscal (RFC).",
            "summarizeBy": "none"
          },
          {
            "name": "Opinión favorable del SAT Actualizada_1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0cf4f20-e19b-4347-a4bb-8bab6c3acd9d",
            "sourceColumn": "Opinión favorable del SAT Actualizada_1",
            "summarizeBy": "none"
          },
          {
            "name": "Copia de carátula de estado de cuenta (No más de 3 meses de antigüedad)_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fd24ae5-6092-4001-9a0b-17f941fe9b14",
            "sourceColumn": "Copia de carátula de estado de cuenta (No más de 3 meses de antigüedad)_2",
            "summarizeBy": "none"
          },
          {
            "name": "Comprobante de domicilio (no más de 3 meses de antigüedad), (OBLIGATORIO)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6940ea33-b7c2-4b0e-a9d0-dce4d3ecefb6",
            "sourceColumn": "Comprobante de domicilio (no más de 3 meses de antigüedad), (OBLIGATORIO)",
            "summarizeBy": "none"
          },
          {
            "name": "Permiso de la SCT.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3573cece-a8fa-4780-9ab0-f21f460ab109",
            "sourceColumn": "Permiso de la SCT.",
            "summarizeBy": "none"
          },
          {
            "name": "Llenado de RFI Del Transportista_3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "485d662d-7220-4ddb-99cd-630d4d806123",
            "sourceColumn": "Llenado de RFI Del Transportista_3",
            "summarizeBy": "none"
          },
          {
            "name": "Alta de Proveedores_4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f89b3078-e159-489d-9780-f377ba8ef324",
            "sourceColumn": "Alta de Proveedores_4",
            "summarizeBy": "none"
          },
          {
            "name": "Firma y llenado de Convenio Comercial.",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfa27606-40d8-4073-9063-0d775da2c9a7",
            "sourceColumn": "Firma y llenado de Convenio Comercial.",
            "summarizeBy": "none"
          },
          {
            "name": "W9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de145f70-1b46-4333-9bf0-baaeee18701d",
            "sourceColumn": "W9",
            "summarizeBy": "none"
          },
          {
            "name": "DATOS BANCARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3474766-85f8-4a38-a9d7-f899c6a2bb9d",
            "sourceColumn": "DATOS BANCARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "Llenado de RFI Del Transportista_5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a7e8c44-4467-411e-a356-ee54bf2920ab",
            "sourceColumn": "Llenado de RFI Del Transportista_5",
            "summarizeBy": "none"
          },
          {
            "name": "Firma y llenado de Convenio Comercial_6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "485d3d8b-6bc9-4830-a183-8857cb7b5d8e",
            "sourceColumn": "Firma y llenado de Convenio Comercial_6",
            "summarizeBy": "none"
          },
          {
            "name": "CERTIFICACIONES (OPCIONAL)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e0e4165-0363-42eb-8e65-335adc76f298",
            "sourceColumn": "CERTIFICACIONES (OPCIONAL)",
            "summarizeBy": "none"
          },
          {
            "name": "Moral, Fisica o Americano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f4dd8c5-ebbb-4185-9e5e-9817b2abd85e",
            "sourceColumn": "Moral, Fisica o Americano",
            "summarizeBy": "none"
          },
          {
            "name": "Capacitacion de seguridad",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2151954-259a-42b7-9ad6-2147b674cdb5",
            "sourceColumn": "Capacitacion de seguridad",
            "summarizeBy": "none"
          },
          {
            "name": "Auditoria ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87220675-b821-4b5a-a45a-74a1a375e6ab",
            "sourceColumn": "Auditoria ",
            "summarizeBy": "none"
          },
          {
            "name": "Calificación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88b9d65b-0325-4994-88c9-9ecdbe7a83ed",
            "sourceColumn": "Calificación",
            "summarizeBy": "none"
          },
          {
            "name": "INDUCCION GENERAL ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40ca54ba-1bbe-4bef-a8fd-44c088158f03",
            "sourceColumn": "INDUCCION GENERAL ",
            "summarizeBy": "none"
          },
          {
            "name": "DMS TRAXPORTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9aab3ba8-d5e3-4224-b502-32ad24494eb5",
            "sourceColumn": "DMS TRAXPORTA",
            "summarizeBy": "none"
          },
          {
            "name": "TORRE DE CONTROL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8213c01c-dee0-4b6c-b4e0-024fb5950a1d",
            "sourceColumn": "TORRE DE CONTROL",
            "summarizeBy": "none"
          },
          {
            "name": "MESA DE CONTROL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a55a42e-ee93-4016-9fba-8841eb0fb4d0",
            "sourceColumn": "MESA DE CONTROL",
            "summarizeBy": "none"
          },
          {
            "name": "EVALUACIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7f906dd-813f-4dc8-8f45-9e28e22e92f3",
            "sourceColumn": "EVALUACIÓN",
            "summarizeBy": "none"
          },
          {
            "name": "CERTIFICADO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0200dd7d-380a-4482-9125-9462391a0a11",
            "sourceColumn": "CERTIFICADO",
            "summarizeBy": "none"
          },
          {
            "name": "KICK OFF POR PROYECTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3efd7d1d-53de-4a62-b23b-49628c1019df",
            "sourceColumn": "KICK OFF POR PROYECTO",
            "summarizeBy": "none"
          },
          {
            "name": "% de Avance General",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63512325-ec73-4847-862e-636dd4d4a6e9",
            "sourceColumn": "% de Avance General",
            "summarizeBy": "none"
          },
          {
            "name": "Nombre del contacto principal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fea54a2f-fe2f-4ddb-9fb6-c307a8223f10",
            "sourceColumn": "Nombre del contacto principal",
            "summarizeBy": "none"
          },
          {
            "name": "Fecha Asignación 1er Viaje",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "963cfb66-1856-4ffe-8ad6-710dacb1e3a5",
            "sourceColumn": "Fecha Asignación 1er Viaje",
            "summarizeBy": "none"
          },
          {
            "name": "DIAS TOTALES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b41873fc-93e6-4d0f-acce-fd1cfa3086f3",
            "sourceColumn": "DIAS TOTALES",
            "summarizeBy": "none"
          },
          {
            "name": "DIAS TOTALES SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b08864f6-4a39-4a51-aa17-a0660eac1df4",
            "sourceColumn": "DIAS TOTALES SAP",
            "summarizeBy": "none"
          },
          {
            "name": "% Avance SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "809453fd-1ac4-4908-b4b2-f6936eaeffca",
            "sourceColumn": "% Avance SAP",
            "summarizeBy": "none"
          },
          {
            "name": "Evaluación SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f4cecdb-0f1f-4d8e-b38c-ffbae2f1cb4e",
            "sourceColumn": "Evaluación SAP",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA INICIO SOLICITUD DOCUMENTOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e51fc024-9809-4fd4-b5d8-bbe55cdf8a6b",
            "sourceColumn": "FECHA INICIO SOLICITUD DOCUMENTOS",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA FIN DOCUMENTOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79b426e3-f459-4cf2-bca3-c0a59ff2dac5",
            "sourceColumn": "FECHA FIN DOCUMENTOS",
            "summarizeBy": "none"
          },
          {
            "name": "DIAS TOTALES DOCUMENTOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cccde37-f562-4e9d-87dd-017ceadd13ce",
            "sourceColumn": "DIAS TOTALES DOCUMENTOS",
            "summarizeBy": "none"
          },
          {
            "name": "% Avance DOCS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd6de858-6f8d-469b-8d35-4f5aff29175a",
            "sourceColumn": "% Avance DOCS",
            "summarizeBy": "none"
          },
          {
            "name": "Evaluación DOCS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17e47abf-75ae-4e45-8605-d3a5951a230e",
            "sourceColumn": "Evaluación DOCS",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA INICIO BLACKTRUST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdd36d58-3031-4b02-90ea-785665d8448e",
            "sourceColumn": "FECHA INICIO BLACKTRUST",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA FIN BLACKTRUST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44e60fbf-aae2-4b58-a65d-45e73ddb75ec",
            "sourceColumn": "FECHA FIN BLACKTRUST",
            "summarizeBy": "none"
          },
          {
            "name": "DIAS TOTALES BLACK TRUST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8ab4420-c4a3-4272-9c6a-6d21c58e850b",
            "sourceColumn": "DIAS TOTALES BLACK TRUST",
            "summarizeBy": "none"
          },
          {
            "name": "% Avance BLACKTRUST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae42344f-f7df-46c0-9c4a-13ab5bfd3f2e",
            "sourceColumn": "% Avance BLACKTRUST",
            "summarizeBy": "none"
          },
          {
            "name": "Evaluación BLACKTRUST",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e45af9c2-b75c-41cc-a6fe-f08c85b5bcb1",
            "sourceColumn": "Evaluación BLACKTRUST",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA INICIO SP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d08125b7-b19e-4eb0-9a53-27b6a65acbaf",
            "sourceColumn": "FECHA INICIO SP",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA FIN SP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d065e8b8-8a15-46dd-9676-cbe9eac1263d",
            "sourceColumn": "FECHA FIN SP",
            "summarizeBy": "none"
          },
          {
            "name": "DIAS TOTALES SP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fb64303-dc2b-4648-b5b0-9c5542f77769",
            "sourceColumn": "DIAS TOTALES SP",
            "summarizeBy": "none"
          },
          {
            "name": "% Avance SP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e58a954-ee1a-49c9-89d8-43761e2f3a6e",
            "sourceColumn": "% Avance SP",
            "summarizeBy": "none"
          },
          {
            "name": "Evaluación SP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75399924-75e6-4daf-85f1-4a3cc0cc2efc",
            "sourceColumn": "Evaluación SP",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA INICIO LEARNING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed06c208-7c51-4d2a-9f62-e8e55496e939",
            "sourceColumn": "FECHA INICIO LEARNING",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA FIN LEARNING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f783bfaa-a997-43e9-9c99-7dfd4383e08c",
            "sourceColumn": "FECHA FIN LEARNING",
            "summarizeBy": "none"
          },
          {
            "name": "DIAS TOTALES LEARNING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "793df0a7-226d-492a-adbe-13755a27aba2",
            "sourceColumn": "DIAS TOTALES LEARNING",
            "summarizeBy": "none"
          },
          {
            "name": "% Avance LEARNING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac8f6c0b-7760-4215-b979-c48248137401",
            "sourceColumn": "% Avance LEARNING",
            "summarizeBy": "none"
          },
          {
            "name": "Evaluación LEARNING",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3149602e-ceb1-4909-912c-fffd1e173131",
            "sourceColumn": "Evaluación LEARNING",
            "summarizeBy": "none"
          },
          {
            "name": "ESTATUS SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e04acd76-37bc-4cc2-9d6c-18b77be22b46",
            "sourceColumn": "ESTATUS SAP",
            "summarizeBy": "none"
          },
          {
            "name": "ESTATUS BLACK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "980dd939-5787-43da-bbba-3a838666fe13",
            "sourceColumn": "ESTATUS BLACK",
            "summarizeBy": "none"
          },
          {
            "name": "ESTATUS FASE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab8c8301-a7be-4abe-954a-52c3f03e4ab6",
            "sourceColumn": "ESTATUS FASE",
            "summarizeBy": "none"
          },
          {
            "name": "ESTATUS DEL PROCESO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2d5f4ee-b860-4d75-9965-edb41a38454c",
            "sourceColumn": "ESTATUS DEL PROCESO",
            "summarizeBy": "none"
          },
          {
            "name": "COMENTARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0127f881-7c34-401e-87b2-f009afb9e379",
            "sourceColumn": "COMENTARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "Contacto telefónico y/o e-amil",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e91bdd8-db37-4341-ba89-3889eb20fcf4",
            "sourceColumn": "Contacto telefónico y/o e-amil",
            "summarizeBy": "none"
          },
          {
            "name": "Opinión positiva del cumplimiento de obligaciones obrero patronales (32-D IMSS)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9acbb32e-e5d5-47ee-a4fc-74ce177932cd",
            "sourceColumn": "Opinión positiva del cumplimiento de obligaciones obrero patronales (32-D IMSS)",
            "summarizeBy": "none"
          },
          {
            "name": "RESPONSABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "719db960-b4b4-462a-a5b3-9e9444b552c9",
            "sourceColumn": "RESPONSABLE",
            "summarizeBy": "none"
          },
          {
            "name": "Column81",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cb28590-cdc5-498f-9408-4b52e55fa682",
            "sourceColumn": "Column81",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "27961122-1c3c-4102-972b-3b8938575a6b",
        "partitions": [
          {
            "name": "Nacional-e398b7c0-70a0-41a4-b08f-25d030e490a6",
            "mode": "import",
            "queryGroup": "BDcarriercare",
            "source": {
              "expression": [
                "let",
                "    Origen = Excel.Workbook(File.Contents(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\BBDD Carrier Care\\BASE DE DATOS - INCORPORACION NUEVOS CARRIERS.xlsx\"), null, true),",
                "    NACIONAL_Sheet = Origen{[Item=\"NACIONAL\",Kind=\"Sheet\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(NACIONAL_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type any}, {\"Column10\", type text}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}, {\"Column25\", type text}, {\"Column26\", type text}, {\"Column27\", type text}, {\"Column28\", type text}, {\"Column29\", type text}, {\"Column30\", type text}, {\"Column31\", type text}, {\"Column32\", type text}, {\"Column33\", type text}, {\"Column34\", type text}, {\"Column35\", type text}, {\"Column36\", type text}, {\"Column37\", type text}, {\"Column38\", type text}, {\"Column39\", type text}, {\"Column40\", type text}, {\"Column41\", type text}, {\"Column42\", type text}, {\"Column43\", type any}, {\"Column44\", type any}, {\"Column45\", type any}, {\"Column46\", type any}, {\"Column47\", type any}, {\"Column48\", type any}, {\"Column49\", type any}, {\"Column50\", type any}, {\"Column51\", type any}, {\"Column52\", type text}, {\"Column53\", type any}, {\"Column54\", type any}, {\"Column55\", type any}, {\"Column56\", type any}, {\"Column57\", type any}, {\"Column58\", type any}, {\"Column59\", type any}, {\"Column60\", type text}, {\"Column61\", type text}, {\"Column62\", type text}, {\"Column63\", type text}, {\"Column64\", type text}, {\"Column65\", type any}, {\"Column66\", type any}, {\"Column67\", type any}, {\"Column68\", type any}, {\"Column69\", type any}, {\"Column70\", type any}, {\"Column71\", type any}, {\"Column72\", type text}}),",
                "    #\"Filas superiores quitadas\" = Table.Skip(#\"Tipo cambiado\",2),",
                "    #\"Encabezados promovidos\" = Table.PromoteHeaders(#\"Filas superiores quitadas\", [PromoteAllScalars=true]),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Encabezados promovidos\", each ([FECHA DE SOLICITUD] <> null and [FECHA DE SOLICITUD] <> \"Cerrada\" and [FECHA DE SOLICITUD] <> \"Cerrado\" and [FECHA DE SOLICITUD] <> \"Recuperada\")),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Filas filtradas\",{{\"FECHA DE SOLICITUD\", type date}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Tipo cambiado1\",{\"Column82\", \"Column83\", \"Column84\", \"Column85\", \"Column86\", \"Column87\", \"Column88\", \"Column89\", \"Column90\", \"Column91\", \"Column92\", \"Column93\", \"Column94\", \"Column95\", \"Column96\", \"Column97\", \"Column98\", \"Column99\", \"Column100\", \"Column101\", \"Column102\", \"Column103\", \"Column104\", \"Column105\", \"Column106\", \"Column107\", \"Column108\", \"Column109\", \"Column110\", \"Column111\", \"Column112\", \"Column113\", \"Column114\", \"Column115\", \"Column116\", \"Column117\", \"Column118\", \"Column119\", \"Column120\", \"Column121\", \"Column122\", \"Column123\", \"Column124\", \"Column125\", \"Column126\", \"Column127\", \"Column128\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Columna1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20113839-833b-4d08-a3d2-2dd2a7fed8c3",
            "sourceColumn": "Columna1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fef6e0da-be5f-4d22-8e60-76dc092e8945",
        "measures": [
          {
            "name": "Días totales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "(CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"Días SAP\")+CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"Días Seguridad\")+CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"Días Learning\")+CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"Días Black trust\")+CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"Días Docs\"))+0",
            "formatString": "0",
            "lineageTag": "b91ac1a0-6030-4c2d-9313-63049ff34501"
          },
          {
            "name": "Prom Evaluación",
            "expression": "AVERAGE('Carrier Care (2)'[Valor Ev])+0",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "94f63b6a-6626-4bdf-9257-534212eed23b"
          },
          {
            "name": "Real",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "HASONEVALUE(",
              "PILARES[Clasificacion]),",
              "SWITCH(",
              "VALUES(",
              "PILARES[ÍNDICE]",
              "), 1,[DIAS SAP],",
              "2,[DIAS DOCS],",
              "3,[DIAS BLACK TRUST],",
              "4,[DIAS SEGURIDAD],",
              "5,[DIAS LEARNING],",
              "6,[Días totales]",
              ")",
              ")"
            ],
            "lineageTag": "6aaf2c03-e244-4401-8234-99fb7153cbb7"
          },
          {
            "name": "DIAS SAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"DIAS TOTALES SAP\")",
            "lineageTag": "b99e3a39-190e-4853-9c23-1b62bef08617"
          },
          {
            "name": "DIAS DOCS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"DIAS TOTALES DOCUMENTOS\")",
            "lineageTag": "e9b69b03-89cb-4c22-9546-9b525c08aa6a"
          },
          {
            "name": "DIAS SEGURIDAD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"DIAS TOTALES SP\")",
            "lineageTag": "d0376903-e60e-4105-bfd4-cf668d900ce0"
          },
          {
            "name": "DIAS LEARNING",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"DIAS TOTALES LEARNING\")",
            "lineageTag": "f123f3fc-1319-4c68-b440-b31b97a26879"
          },
          {
            "name": "DIAS BLACK TRUST",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[Valor Dias]),'Carrier Care (2)'[Atributo]=\"DIAS TOTALES BLACK TRUST\")",
            "lineageTag": "1738720c-68bd-4157-ac76-777f09b6674c"
          },
          {
            "name": "Objetivo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "HASONEVALUE(",
              "PILARES[Clasificacion]),",
              "SWITCH(",
              "VALUES(",
              "PILARES[ÍNDICE]",
              "), 1,2,",
              "2,6,",
              "3,2,",
              "4,8,",
              "5,4,",
              "6,[ObjetivoT.Alta]",
              ")",
              ")"
            ],
            "lineageTag": "f4dfb031-28dd-46c9-ba91-15ea6faee2b9"
          },
          {
            "name": "Formato",
            "expression": "SWITCH(TRUE(), [Calificación]<90,\"#AC0000\",[Calificación]>=90 && [Calificación]<95,\"#FFC000\",\"#ADBA02\")",
            "lineageTag": "24381778-4809-4fc8-93b9-611dbb414f2b"
          },
          {
            "name": "Cumplimiento",
            "expression": "DIVIDE([Objetivo],[Months to show_Real])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "97a99d32-5a9c-4b62-b782-bcd30f336822"
          },
          {
            "name": "Calificación",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SWITCH(TRUE(),[Cumplimiento]<=1,[Cumplimiento]*100,120)",
            "formatString": "0",
            "lineageTag": "d4efc017-ddb9-4994-bd72-95dc05532d91"
          },
          {
            "name": "StartValue",
            "expression": "0",
            "formatString": "0",
            "lineageTag": "abf6c732-904d-42eb-8cb2-54eef5d7f972"
          },
          {
            "name": "End Value",
            "expression": "120",
            "formatString": "0",
            "lineageTag": "8b6ea4ce-6d39-41c3-8706-135b229b1f50"
          },
          {
            "name": "StartValue2",
            "expression": "93",
            "formatString": "0",
            "lineageTag": "13c1ef59-e53b-4b0e-a255-c94e6a9b8cb0"
          },
          {
            "name": "End Value2",
            "expression": "97",
            "formatString": "0",
            "lineageTag": "fedb7003-b4bb-4fa4-a5b5-495fd08bfd02"
          },
          {
            "name": "1 Prom Dias proceso terminado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Días totales]",
            "formatString": "0",
            "lineageTag": "0c62e61e-e693-47d0-9fee-afde29ecacfb"
          },
          {
            "name": "%AvanceGeneral",
            "expression": "AVERAGE('Carrier Care (2)'[% de Avance General])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "4e2b833e-91bb-4e2e-93c9-61a759952f95"
          },
          {
            "name": "COMPLETOS",
            "expression": "SUMX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),IF([%AvanceGeneral]=1,1,0))",
            "formatString": "0",
            "lineageTag": "2ace9bd0-82cf-478f-81b8-a0fda3adcc9b"
          },
          {
            "name": "2 en tiempo vs fuera de tiempo",
            "expression": [
              "VAR ENTIEMPO=COUNTX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),CALCULATE(COUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),'Carrier Care (2)'[En tiempo/fuera de tiempo]=\"en tiempo\"))",
              "        VAR FUERA=COUNTX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),CALCULATE(COUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),'Carrier Care (2)'[En tiempo/fuera de tiempo]=\"fuera de tiempo\"))",
              "        return ",
              "        DIVIDE(ENTIEMPO,FUERA+ENTIEMPO)+0"
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "69d566c6-5c50-4302-a0e3-63a192fcf263"
          },
          {
            "name": "2 en tiempo vs fuera de tiempo()",
            "expression": [
              "VAR ENTIEMPO=COUNTX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),CALCULATE(COUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),'Carrier Care (2)'[En tiempo/fuera de tiempo]=\"en tiempo\"))+0",
              "        VAR FUERA=COUNTX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),CALCULATE(COUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),'Carrier Care (2)'[En tiempo/fuera de tiempo]=\"fuera de tiempo\"))+0",
              "        return ",
              "        ENTIEMPO&\" vs \"&FUERA"
            ],
            "lineageTag": "608a4210-47de-4ff6-a4ec-2b2f37a5f649"
          },
          {
            "name": "4Cuenta carrier fuera de tiempo por área",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR ENTIEMPO=COUNTX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),CALCULATE(DISTINCTCOUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),'Carrier Care (2)'[Objetivo días por area2]=\"en tiempo\"))",
              "        VAR FUERA=COUNTX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),CALCULATE(DISTINCTCOUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),'Carrier Care (2)'[Objetivo días por area2]=\"fuera de tiempo\"))",
              "        return ",
              "        FUERA"
            ],
            "lineageTag": "4dec3bb0-a0b9-475c-bd31-3e4c9d3683e3"
          },
          {
            "name": "AvanceLearning",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[ValorAvance]),'Carrier Care (2)'[Atributo]=\"% Avance Learning\")",
            "lineageTag": "f2382c96-35fb-4e8b-a187-f020733dd071"
          },
          {
            "name": "Dias promedio capacitaciones terminadas",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGEx(allselected('Carrier Care (2)'[Proveedor/Nombre Comercial]),IF([AvanceLearning]=0.20,[DIAS LEARNING],BLANK()))",
            "lineageTag": "c70b2c4c-1d21-4b12-a8db-b5f44b914f35"
          },
          {
            "name": "Pendientes de capacitación",
            "expression": "CALCULATE(DISTINCTCOUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),NOT(ISBLANK('Carrier Care (2)'[EstatusLearning])))+0",
            "formatString": "0",
            "lineageTag": "05c11203-e76a-4fd5-bb59-900a0bc41498"
          },
          {
            "name": "ObjetivoT.Alta",
            "expression": [
              "SWITCH(TRUE(),",
              "                  SELECTEDVALUE(calendarconection[Quarter])=1 && SELECTEDVALUE(calendarconection[Year])=2023,15,",
              "                  SELECTEDVALUE(calendarconection[Quarter])=2 && SELECTEDVALUE(calendarconection[Year])=2023,10,",
              "                  SELECTEDVALUE(calendarconection[Quarter])=3 && SELECTEDVALUE(calendarconection[Year])=2023,7,",
              "                  SELECTEDVALUE(calendarconection[Quarter])=4 && SELECTEDVALUE(calendarconection[Year])=2023,5",
              "                  )"
            ],
            "formatString": "0",
            "lineageTag": "e7eee47e-7a16-42dc-a43c-276afef1ba66"
          },
          {
            "name": "Months to show",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [DiasRCTotales],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              "",
              "",
              "                                "
            ],
            "lineageTag": "945d587b-11f5-49a7-a560-1a2172fa1600"
          },
          {
            "name": "Months to show_Real",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "HASONEVALUE(",
              "PILARES[Clasificacion]),",
              "SWITCH(",
              "VALUES(",
              "PILARES[ÍNDICE]",
              "), 1,[Months to show_DiasSAP],",
              "2,[Months to show_DiasDocs],",
              "3,[Months to show_DiasBlack],",
              "4,[Months to show_DiasSP],",
              "5,[Months to show_DiasLearning],",
              "6,[Months to show]",
              ")",
              ")"
            ],
            "lineageTag": "c7d4d943-6ff2-401a-aba5-b86bda621e57"
          },
          {
            "name": "Textoperiodo",
            "expression": "\"Carriers en\"&\" \"&SELECTEDVALUE(calendarconection[Monthname])&\"+ \"&[MonthRange]-1&\" meses atrás\"",
            "lineageTag": "fd894c97-b3ed-4c44-9617-988e7a4f4e63"
          },
          {
            "name": "AvanceSAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[ValorAvance]),'Carrier Care (2)'[Atributo]=\"% Avance SAP\")",
            "lineageTag": "574100ff-80c8-4124-8d55-4d16b1db2fd3"
          },
          {
            "name": "AvanceDOCS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[ValorAvance]),'Carrier Care (2)'[Atributo]=\"% Avance DOCS\")",
            "lineageTag": "ce90e36a-c110-4f67-b569-071b8534aa4f"
          },
          {
            "name": "AvanceSP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[ValorAvance]),'Carrier Care (2)'[Atributo]=\"% Avance SP\")",
            "lineageTag": "d31d1376-9f5d-4959-b6aa-fbf0de7f430b"
          },
          {
            "name": "AvanceBLACKTRUST",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('Carrier Care (2)'[ValorAvance]),'Carrier Care (2)'[Atributo]=\"% Avance BLACKTRUST\")",
            "lineageTag": "ca813b69-c1f5-4b28-acc1-a2ff991e5890"
          },
          {
            "name": "Pend_cap",
            "expression": "CALCULATE(DISTINCTCOUNT('Carrier Care (2)'[Proveedor/Nombre Comercial]),'Carrier Care (2)'[EstatusLearning_2]=1,REMOVEFILTERS(calendarconection))",
            "formatString": "0",
            "lineageTag": "676e0a2d-5333-4959-b49b-c8a6a57fe24e"
          },
          {
            "name": "Pend_cap_2",
            "expression": "CALCULATE([Months to show_CCarriers],FILTER(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),[Months to show_pend_cap]>0))",
            "formatString": "0",
            "lineageTag": "fee049e8-333e-40be-bd8d-b43c0454883f"
          }
        ],
        "partitions": [
          {
            "name": "Medidas-ec230e3f-94ef-4ab1-99d6-907a0fb634df",
            "mode": "import",
            "queryGroup": "BDcarriercare",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Columna1\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_41d2e0e5-9585-4858-915c-164254b125a7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "97fb27a4-6687-45d7-8c29-4799f40c573a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "df287539-19b5-4427-80b3-62c8adaa08e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "792ce6eb-2308-47e4-bce5-cbcc05d37dff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d083cdfd-6cc5-4d9b-a54f-bb774eed099f",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "63ffcf1f-a615-430f-865f-9db0bb63b7c9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fc0c812d-36a2-4e02-bf6c-8eb79e20d46e",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "400d7150-976f-4ee0-ba59-2189fda732c4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "b08a44e6-796e-4293-9940-028a30dc1965",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "da4011ab-97ee-4ded-a010-2a0ac3aa1722",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "bddae2d7-6901-41e6-bb2b-98f1167de9eb",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "f45ea11e-3658-48a3-9710-e5355f9978bf",
                "ordinal": 3
              }
            ],
            "lineageTag": "461f6727-6314-4dcd-a48f-0b2e58fa9c6b"
          }
        ],
        "isHidden": true,
        "lineageTag": "6b448a1d-71ee-4639-9689-75410e3a1ec1",
        "partitions": [
          {
            "name": "LocalDateTable_41d2e0e5-9585-4858-915c-164254b125a7-d149cf6c-05c0-4843-8992-228c606d77c9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Nacional'[FECHA DE SOLICITUD])), 1, 1), Date(Year(MAX('Nacional'[FECHA DE SOLICITUD])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "505d46366ce8443d89d14768cd7b1e1c"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6b03ae70-7340-4978-9b5c-3ac5688d1136",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_f70aa27b-5a03-432c-a48a-7e9b1c762409"
                },
                "isDefault": true,
                "relationship": "db47e2cf-aedf-4ce1-bde5-b2b15a85a371"
              }
            ]
          }
        ],
        "lineageTag": "a29bc21f-3eee-4f28-9f83-a8ebc52568ca",
        "partitions": [
          {
            "name": "Calendario-fb4f2a20-7601-476b-af66-a5460fed15ba",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(MIN(Fechas[Min]),MAX(Fechas[Min]))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f70aa27b-5a03-432c-a48a-7e9b1c762409",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7cb865f2-a032-4dea-987e-447ff0e5a750",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "04f6336c-af9f-42c9-b9ca-9e881bb7d26e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b4d11bd6-bd6a-4ec6-9ae7-8f7e37da94eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7294a633-a71b-498e-9c32-1e69bdd6962b",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "25fc2151-41a2-4cde-b1c9-bbe49c8ce10a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "62503e9c-ad4d-4e24-963d-93767d4b7524",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4c9eeef4-c90e-432c-87ea-1ade35374027",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "099c222c-1432-46e5-bd03-6a3c7b8a12bd",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d34876ef-1c21-41b4-94dc-783cfae8cd57",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "26901596-6e06-4ced-840c-eadcd580a6d7",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "5e2b0daf-bfa5-430e-a026-9df1a988c648",
                "ordinal": 3
              }
            ],
            "lineageTag": "00da6eb6-d4cc-404f-9b2b-1d587eabf036"
          }
        ],
        "isHidden": true,
        "lineageTag": "be66f8dd-6122-41b5-b01e-e61250a569c5",
        "partitions": [
          {
            "name": "LocalDateTable_f70aa27b-5a03-432c-a48a-7e9b1c762409-bbce8abd-2db4-438e-b1da-037686b626b9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendario'[Date])), 1, 1), Date(Year(MAX('Calendario'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "calendarconection",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0616dd762d1f410cb950de5d0c51457e"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "74faa1de-4dcc-4b0a-bad2-cc8d0943b930",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Monthname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(calendarconection[Date],\"mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "0e1ad460-0aa4-4a3b-86ee-cfcd26cee079",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(calendarconection[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6da4cca3-6ef8-4e18-80e0-7e37f95dfc2f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "QUARTER(calendarconection[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "55ba62fb-3a90-4c31-82ec-2e95529c3fb3",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(calendarconection[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8f1fd042-e38c-4e27-a868-a1ddc388f623",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM(calendarconection[Date],21)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8e40cfc0-f541-4d78-bdfc-eea5319d48f2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "FORMAT(calendarconection[Date],\"general number\")",
            "formatString": "0",
            "lineageTag": "8a17f803-dc92-43c2-abde-fbec1802b4e8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Column 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RANK.EQ(calendarconection[Column],calendarconection[Column],ASC)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ac8a8a2e-a98a-4ade-8d8a-254500901c00",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Week2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM(calendarconection[Date],2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "40901213-6ce5-4396-915e-a879b44f3a83",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Anio-Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "calendarconection[Year]*100+calendarconection[Week2]",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6e188398-d2e7-4c09-bebd-6ec48372369b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "RankAnio-Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "expression": "RANKX(calendarconection,calendarconection[Anio-Semana],,ASC,Dense)",
            "formatString": "0",
            "lineageTag": "65273fb9-e408-4428-ad79-161f72da41de",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "29semanasContempladas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "expression": [
              "var m1=MAX(calendarconection[RankAnio-Semana])",
              "           var m2=m1-29",
              "           var m3= SWITCH(TRUE(), calendarconection[RankAnio-Semana]>=m2 && calendarconection[RankAnio-Semana]<=m1,1,BLANK())",
              "           return",
              "           m3"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "60f45833-f315-48f0-9e0a-ae3a85bf8954",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "calendarconection[Monthname]&\"_\"&calendarconection[Year]",
            "isDataTypeInferred": true,
            "lineageTag": "1e678ee9-3106-4255-a55e-4007b8c15c02",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "baed3f25-3cf5-4073-afa1-92f406762af7",
        "partitions": [
          {
            "name": "calendarconection-b89c550b-9117-47af-bced-f619183a6e8a",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(\"01/01/2022\",TODAY())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Incidencias",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FOLIO PQR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6925cc11-f13d-4a88-8b09-5803dc99d7f2",
            "sourceColumn": "FOLIO PQR",
            "summarizeBy": "none"
          },
          {
            "name": "CARRIER ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe447556-1ff9-4284-96e9-ad1d8b7715b7",
            "sourceColumn": "CARRIER ",
            "summarizeBy": "none"
          },
          {
            "name": "RAZON SOCIAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7e8de6c-13cc-4974-9849-6d8880a0f303",
            "sourceColumn": "RAZON SOCIAL",
            "summarizeBy": "none"
          },
          {
            "name": "ASUNTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2faee00-f5c3-446d-b4a4-544877735dbb",
            "sourceColumn": "ASUNTO",
            "summarizeBy": "none"
          },
          {
            "name": "DEPARTAMENTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17f909e7-4578-4108-9f37-c959a2a72245",
            "sourceColumn": "DEPARTAMENTO",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA DE RECEPCIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "8af587bd-459b-4c0f-90aa-f5f1357f1d22",
            "sourceColumn": "FECHA DE RECEPCIÓN",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_ee042d8e-6b6a-4c95-a023-0597a13a14e7"
                },
                "isDefault": true,
                "relationship": "329662f2-ee5a-4e29-aa3c-933e7957d79a"
              }
            ]
          },
          {
            "name": "FECHA DE ASIGNACIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "5ac8dd47-a746-4e2c-a607-91592f29276e",
            "sourceColumn": "FECHA DE ASIGNACIÓN",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_995a9f87-863d-49c7-8a02-e1834cd06213"
                },
                "isDefault": true,
                "relationship": "505be358-7b77-43bf-a5bb-446a1c6580eb"
              }
            ]
          },
          {
            "name": "RESPONSABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a36a22dd-ef33-4e16-a54b-d2fe2e5b2ca1",
            "sourceColumn": "RESPONSABLE",
            "summarizeBy": "none"
          },
          {
            "name": "ESTATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "013b9b35-75ed-4a0b-a15d-e3924126485f",
            "sourceColumn": "ESTATUS",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA DE CIERRE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "56dbecd4-f5ce-41f2-a460-e463b042abf9",
            "sourceColumn": "FECHA DE CIERRE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_fca9d86d-6923-4da5-bbeb-e5ade30b71dc"
                },
                "isDefault": true,
                "relationship": "c3854045-0228-4ff8-a0b4-9cd3515e9617"
              }
            ]
          },
          {
            "name": "DÍAS ABIERTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7a564549-c714-4ee6-9781-8fd7ae010fea",
            "sourceColumn": "DÍAS ABIERTO",
            "summarizeBy": "sum"
          },
          {
            "name": "DÍAS TOTALES SOLUCIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c5d101d-8b43-4ed1-bac5-1c6f004b58b1",
            "sourceColumn": "DÍAS TOTALES SOLUCIÓN",
            "summarizeBy": "sum"
          },
          {
            "name": "Comentarios",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbe96d5f-f84c-4327-9aa0-a81dc59a6b53",
            "sourceColumn": "Comentarios",
            "summarizeBy": "none"
          },
          {
            "name": "Rango Dias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(Incidencias[FECHA DE CIERRE]=BLANK(),BLANK(),SWITCH(TRUE(),",
              "                   Incidencias[DÍAS TOTALES SOLUCIÓN]>=0 && Incidencias[DÍAS TOTALES SOLUCIÓN]<=3,\"<=3 dias\",",
              "                    Incidencias[DÍAS TOTALES SOLUCIÓN]>3 && Incidencias[DÍAS TOTALES SOLUCIÓN]<=6,\"3-6 dias\",",
              "                    Incidencias[DÍAS TOTALES SOLUCIÓN]>6 && Incidencias[DÍAS TOTALES SOLUCIÓN]<=12,\"6-12 dias\",",
              "                    Incidencias[DÍAS TOTALES SOLUCIÓN]>12,\">12 dias\",BLANK()))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "80891914-2e36-4d8c-aeb2-26848b4547a1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "LINEA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "552e1962-152a-4800-b144-0eec69ba93fd",
            "sourceColumn": "LINEA",
            "summarizeBy": "none"
          },
          {
            "name": "Tiempo Primer Contacto (hrs)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "VAR T_1 = Incidencias[FECHA DE ASIGNACIÓN]-Incidencias[FECHA DE RECEPCIÓN]",
              "                               VAR T_2 = IF(Incidencias[FECHA DE RECEPCIÓN]=BLANK() || Incidencias[FECHA DE ASIGNACIÓN]=BLANK(),BLANK(),T_1*24)",
              "                               RETURN",
              "                               T_2"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1b56a262-f158-4c57-9333-dee4c3f2463b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Rango Tiempo Primer Contacto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(Incidencias[FECHA DE RECEPCIÓN]=BLANK() || Incidencias[FECHA DE ASIGNACIÓN]=BLANK(),BLANK(),SWITCH(TRUE(),",
              "                   Incidencias[Tiempo primer contacto (hrs)]>=0 && Incidencias[Tiempo primer contacto (hrs)]<=6,\"<=6 hrs\",",
              "                    Incidencias[Tiempo primer contacto (hrs)]>6 && Incidencias[Tiempo primer contacto (hrs)]<=12,\"6-12 hrs\",",
              "                    Incidencias[Tiempo primer contacto (hrs)]>12 && Incidencias[Tiempo primer contacto (hrs)]<=24,\"12-24 hrs\",",
              "                    Incidencias[Tiempo primer contacto (hrs)]>24 && Incidencias[Tiempo primer contacto (hrs)]<=48,\"24-48 hrs\",",
              "                    Incidencias[Tiempo primer contacto (hrs)]>48,\">48 hrs\",BLANK()))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8840dadd-0b0e-41b4-a613-185d0e4b580c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MesCierre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(Incidencias[FECHA DE CIERRE],\"mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "e7a293be-ec74-4a4f-b483-4c2a488bc8e8",
            "sortByColumn": "MesCierreNum",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "AnioCierre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(Incidencias[FECHA DE CIERRE])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "f5c9ef24-a264-4304-b9f2-4cd6fc194ccf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MesCierreNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(Incidencias[FECHA DE CIERRE])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "122deaed-50fd-4b6b-98d2-6cd2bfc3df2e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "TIEMPO DE  PRIMER CONTACTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3497eef9-3cb9-4046-8470-205756307239",
            "sourceColumn": "TIEMPO DE  PRIMER CONTACTO",
            "summarizeBy": "none"
          },
          {
            "name": "SITUACIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f20f2d9-cca7-4875-95df-ad94f775fdbb",
            "sourceColumn": "SITUACIÓN",
            "summarizeBy": "none"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7c02cad-c2c3-4fb8-b9d3-118c73439d89",
            "sourceColumn": "Mes",
            "summarizeBy": "none"
          },
          {
            "name": "Termino de cierre correcto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "264cb411-72ab-407e-8714-60e16e55d74a",
            "sourceColumn": "Termino de cierre correcto",
            "summarizeBy": "none"
          },
          {
            "name": "Situación exacta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82773f76-e18f-4f84-8d44-d62bbb6fe149",
            "sourceColumn": "Situación exacta",
            "summarizeBy": "none"
          },
          {
            "name": "SITUACIÓN EN OPERACIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28b7f2bd-3516-48d6-9156-89d8d1cf49c0",
            "sourceColumn": "SITUACIÓN EN OPERACIÓN",
            "summarizeBy": "none"
          },
          {
            "name": "Cliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d0f750b-912e-46e8-836a-1cc168662d9a",
            "sourceColumn": "Cliente",
            "summarizeBy": "none"
          },
          {
            "name": "Adeudo aproximado PQR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15a04ebc-84ad-466f-af8e-8defdbcf4e77",
            "sourceColumn": "Adeudo aproximado PQR",
            "summarizeBy": "none"
          },
          {
            "name": "Adeudo aproximado NAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58ef37ee-00fa-4ec8-a2cc-eb56346ddbc8",
            "sourceColumn": "Adeudo aproximado NAL",
            "summarizeBy": "none"
          },
          {
            "name": "NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ef93998-b453-4168-b3d5-b01b62a4dd7b",
            "sourceColumn": "NPS",
            "summarizeBy": "none"
          },
          {
            "name": "Comentarios NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf9cdbf4-19e3-44c5-bece-8b6e028a4581",
            "sourceColumn": "Comentarios NPS",
            "summarizeBy": "none"
          },
          {
            "name": "Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM(Incidencias[FECHA DE CIERRE],21)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1cdc6ffe-87cd-4160-afe3-30febd193986",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Dias anteriores",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a9f7e67-ad41-4dc0-9b42-718de12db52a",
            "sourceColumn": "Dias anteriores",
            "summarizeBy": "none"
          },
          {
            "name": "AÑO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60117e0e-9031-466e-8560-7fba48c0c86e",
            "sourceColumn": "AÑO",
            "summarizeBy": "none"
          },
          {
            "name": "Prioridad de montos y antigüedad",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b482a97e-d928-42d1-8727-8851f0bf6ffa",
            "sourceColumn": "Prioridad de montos y antigüedad",
            "summarizeBy": "none"
          },
          {
            "name": "Monto por asociar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f21508d-0533-4378-9c1e-67e1943cbe24",
            "sourceColumn": "Monto por asociar",
            "summarizeBy": "none"
          },
          {
            "name": "Confirmacion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78ad9b76-86e7-4b0d-8f2f-9f6b4ec42fe9",
            "sourceColumn": "Confirmacion",
            "summarizeBy": "none"
          },
          {
            "name": "Prioridad",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b860e52-a363-4aa0-8d18-94473b719818",
            "sourceColumn": "Prioridad",
            "summarizeBy": "none"
          },
          {
            "name": "Asignacion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f57f83d2-ff4a-4b1e-9967-9b561a722e60",
            "sourceColumn": "Asignacion",
            "summarizeBy": "none"
          },
          {
            "name": "Revisión George",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2428af18-7a41-4f6f-9744-08f61699c77e",
            "sourceColumn": "Revisión George",
            "summarizeBy": "none"
          },
          {
            "name": "Ultimo load TMS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5ef1ff4-075c-4a04-b270-805848cdcaff",
            "sourceColumn": "Ultimo load TMS",
            "summarizeBy": "none"
          },
          {
            "name": "Observaciones",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "135d14c0-9350-4e74-80e2-b4c4a2150b59",
            "sourceColumn": "Observaciones",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "325b67a3-2543-420c-bb9c-50283a290014",
        "measures": [
          {
            "name": "%Cierre",
            "expression": [
              "VAR totalxmes=CALCULATE([Cuenta de Asunto],ALLEXCEPT(Incidencias,Incidencias[AnioCierre],Incidencias[MesCierre]))",
              "          VAR Porcentaje=DIVIDE([Cuenta de Asunto],totalxmes)",
              "          RETURN",
              "          Porcentaje"
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "a1411a8e-cf0f-47c2-a39b-371251507fce"
          }
        ],
        "partitions": [
          {
            "name": "Incidencias-517d56a4-bebb-4b9b-8d1d-101524f4fd65",
            "mode": "import",
            "queryGroup": "Incidencias Carrier Care",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\GENERAL\\MASTER TRACKING PQR.xlsx\"), null, true),",
                "    Tabla1_Table = Source{[Item=\"PQR\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Tabla1_Table,{{\"FOLIO PQR\", Int64.Type}, {\"CARRIER \", type text}, {\"RAZON SOCIAL\", type any}, {\"ASUNTO\", type text}, {\"DEPARTAMENTO\", type text}, {\"FECHA DE RECEPCIÓN\", type date}, {\"FECHA DE ASIGNACIÓN\", type date}, {\"RESPONSABLE\", type text}, {\"ESTATUS\", type text}, {\"FECHA DE CIERRE\", type date}, {\"DÍAS ABIERTO\", Int64.Type}, {\"DÍAS TOTALES SOLUCIÓN\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([#\"CARRIER \"] <> null)),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"LINEA\", type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type1\", {\"FOLIO PQR\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ee042d8e-6b6a-4c95-a023-0597a13a14e7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "90b04a1f-91a9-4203-9d5f-33c8855c3aba",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "78ee652a-e93f-4d84-99ed-ebda8f8604a6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d403ff11-e8a7-4886-ade1-0f85e68f8049",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6b796fb8-fa39-49bb-8d94-3ad6f868d970",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "64c3a546-e70a-493e-a56a-7c07bd3b812b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cfebb1f3-3eda-4d86-b9f2-4bcc6c72e1dc",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "60da9cbf-5bb0-4f24-9a0a-8076691ca2fb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "d0bbb783-e746-43b7-87c1-5e6593505516",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "501ddcf7-8415-4b52-a5fa-25d6b3e4f089",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "1c343dd1-693b-4b39-a065-a0970bb0648f",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "e3284501-a420-4912-a503-972de55d26ee",
                "ordinal": 3
              }
            ],
            "lineageTag": "7b6d1984-1632-4256-a133-f2314a7481e5"
          }
        ],
        "isHidden": true,
        "lineageTag": "bfe4b69b-370d-4cb5-957b-b12f30169b70",
        "partitions": [
          {
            "name": "LocalDateTable_ee042d8e-6b6a-4c95-a023-0597a13a14e7-698436c9-b02f-4c6a-9766-6e75bf221fe1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Incidencias'[FECHA DE RECEPCIÓN])), 1, 1), Date(Year(MAX('Incidencias'[FECHA DE RECEPCIÓN])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_995a9f87-863d-49c7-8a02-e1834cd06213",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "069d94f4-6fb0-4ee3-a825-cf5cdc76b468",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "00dbc65d-f89a-4cec-bad0-f87766b432cf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5ea5218a-9cc7-4e9d-af07-e87941241cc4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f755620-ba53-4503-996f-672759da2153",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9e6ba013-7f11-4469-a621-f77e3286304b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "730076d4-a28f-46aa-a87e-ac4343a3244d",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a0f29960-9047-4d75-8151-b4fdc00d3e94",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "f4d57206-75d5-42d7-b41d-60a7ac1499ab",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "dc3f6d0c-67b4-408e-8026-dc8ac8111580",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "810bddeb-8e47-453e-aebe-def396afcad5",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "17369a0e-9622-40c3-a442-378e316b2ab7",
                "ordinal": 3
              }
            ],
            "lineageTag": "f4f10728-e519-489f-b147-410cf35fb8a2"
          }
        ],
        "isHidden": true,
        "lineageTag": "a4d03848-2f4a-4c9d-a921-e817272b3115",
        "partitions": [
          {
            "name": "LocalDateTable_995a9f87-863d-49c7-8a02-e1834cd06213-fe45a4e1-e12e-47b5-b722-124d99fede19",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Incidencias'[FECHA DE ASIGNACIÓN])), 1, 1), Date(Year(MAX('Incidencias'[FECHA DE ASIGNACIÓN])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_fca9d86d-6923-4da5-bbeb-e5ade30b71dc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5145ebba-285a-4456-a1e5-72f86d34f6fb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "59ae234f-d0b4-4d2a-a44d-69af95782e16",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f314d854-97b0-4fb2-9f53-8badbba87754",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "01617a5f-d650-4e8e-a471-e4b98e9f72db",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8916aed5-38db-4b83-877a-6b82d1037a48",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2e8005f1-9663-4344-b8ff-a21c14343e6a",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ffc22cb1-b3e7-4448-8bdb-ffea095ac6ca",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "96979eee-a9ec-4eee-a975-9a648bb2c8da",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "2a3ff56b-e009-42a9-b238-096d4670a39b",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "3354cd55-a7cb-4917-bc84-8227b80153c0",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "358258c2-4a51-4e2f-a0b9-b2c0609d5fee",
                "ordinal": 3
              }
            ],
            "lineageTag": "a1aa0e6e-d6cf-4ae6-ba02-a0cd2082a8c2"
          }
        ],
        "isHidden": true,
        "lineageTag": "ce7e608b-db8e-461f-a3a2-f4a766985cf7",
        "partitions": [
          {
            "name": "LocalDateTable_fca9d86d-6923-4da5-bbeb-e5ade30b71dc-529aa104-5f0c-46bd-8ea9-629f16cc15b2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Incidencias'[FECHA DE CIERRE])), 1, 1), Date(Year(MAX('Incidencias'[FECHA DE CIERRE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "FechasIncidencias",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FOLIO PQR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8d0fc2c-be03-4b0c-9d6f-e89b9408660d",
            "sourceColumn": "FOLIO PQR",
            "summarizeBy": "none"
          },
          {
            "name": "Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ab95041c-23b5-4ace-965a-ce3971c76451",
            "sourceColumn": "Min",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1b484549-7c68-4b3f-b28a-d52e05b86087",
        "partitions": [
          {
            "name": "FechasIncidencias-41eb7c19-4b97-4080-8ee0-05d36e9ab183",
            "mode": "import",
            "queryGroup": "Incidencias Carrier Care",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\GENERAL\\MASTER TRACKING PQR.xlsx\"), null, true),",
                "    Tabla1_Table = Source{[Item=\"PQR\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Tabla1_Table,{{\"FOLIO PQR\", Int64.Type}, {\"CARRIER \", type text}, {\"RAZON SOCIAL\", type any}, {\"ASUNTO\", type text}, {\"DEPARTAMENTO\", type text}, {\"FECHA DE RECEPCIÓN\", type date}, {\"FECHA DE ASIGNACIÓN\", type date}, {\"RESPONSABLE\", type text}, {\"ESTATUS\", type text}, {\"FECHA DE CIERRE\", type date}, {\"DÍAS ABIERTO\", Int64.Type}, {\"DÍAS TOTALES SOLUCIÓN\", Int64.Type}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([#\"CARRIER \"] <> null)),",
                "    #\"Grouped Rows\" = Table.Group(#\"Filtered Rows\", {\"FOLIO PQR\"}, {{\"Min\", each List.Min([FECHA DE RECEPCIÓN]), type nullable date}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Grouped Rows\", each ([Min] <> null)),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows1\", {\"FOLIO PQR\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NPS_NACIONAL",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CARRIER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e6ac69e-d2f9-4f52-aaa7-41365a211e19",
            "sourceColumn": "CARRIER",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f348f959-04bb-4768-b5ec-d5e31d724ace",
            "sourceColumn": "FECHA",
            "summarizeBy": "none"
          },
          {
            "name": "CONTACTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8232a5f0-f225-49b1-a6c9-4acd8fcfebe9",
            "sourceColumn": "CONTACTO",
            "summarizeBy": "none"
          },
          {
            "name": "TELEFONO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44f26644-7d5d-4403-be5a-b40179204104",
            "sourceColumn": "TELEFONO",
            "summarizeBy": "none"
          },
          {
            "name": "RESPONSABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92d5d042-68cd-4432-a21a-e79ab43b966d",
            "sourceColumn": "RESPONSABLE",
            "summarizeBy": "none"
          },
          {
            "name": "Comentarios",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d2a30d1-a0f1-4a6a-867b-393630a64ca9",
            "sourceColumn": "Comentarios",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b57be58-93b1-4958-a7d9-b8b37fb3f0b0",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "Attribute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd9053c0-98e3-4374-a37d-01536c1e0bc3",
            "sourceColumn": "Attribute",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f7f9ec0c-4712-4934-97d5-09a3032c81a0",
            "sourceColumn": "Value",
            "summarizeBy": "sum"
          },
          {
            "name": "ID REGISTROS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dfba4be-7b61-41e0-af30-3ec04a6eb7b0",
            "sourceColumn": "ID REGISTROS",
            "summarizeBy": "none"
          },
          {
            "name": "NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "60b4f792-d323-4657-9e39-173c06012a25",
            "sourceColumn": "NPS",
            "summarizeBy": "sum"
          },
          {
            "name": "ClasificaciónNPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(TRUE(),",
              "              NPS_NACIONAL[NPS]=BLANK(),\"Sin Respuesta\",",
              "              NPS_NACIONAL[NPS]<7,\"Detractor\",",
              "              NPS_NACIONAL[NPS]>8,\"Promotor\",\"Neutro\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0064cfa0-9912-4b25-891e-ee958f3c3e27",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52e174e6-ec56-4ecb-9ece-04aa3aeab71f",
            "sourceColumn": "Periodo",
            "summarizeBy": "none"
          },
          {
            "name": "G",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e09e8500-3119-4772-808e-87fddb3a1c93",
            "sourceColumn": "G",
            "summarizeBy": "none"
          },
          {
            "name": "Correo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0794f978-30e5-4c32-acee-b9eec06c786f",
            "sourceColumn": "Correo",
            "summarizeBy": "none"
          },
          {
            "name": "NOMBRE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5d8beb4-a343-4ef4-8d1d-5d2cde94059a",
            "sourceColumn": "NOMBRE",
            "summarizeBy": "none"
          },
          {
            "name": "COMENTARIOS 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7119845-75ac-47db-bc40-2b9b806e189a",
            "sourceColumn": "COMENTARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "Column12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55f1bd9f-ec5b-4eef-b797-4d61fd143fce",
            "sourceColumn": "Column12",
            "summarizeBy": "none"
          },
          {
            "name": "HOMOLOGACIÓN DE COMENTARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da3aeff2-a1ba-45be-928d-7d65b902f5d3",
            "sourceColumn": "HOMOLOGACIÓN DE COMENTARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf1efb68-5e7e-41ac-b229-92544d1f904a",
            "sourceColumn": "Column11",
            "summarizeBy": "none"
          },
          {
            "name": "ESTATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9112af42-14fc-4b44-8ecb-39d141e66579",
            "sourceColumn": "ESTATUS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "61b40c10-9c60-43bb-beb7-b42c79b59874",
        "partitions": [
          {
            "name": "NPS_NACIONAL-fd2ab9ac-7d9c-482d-80aa-ffc0f02f593b",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"CARRIER\", type text}, {\"FECHA\", type date}, {\"CONTACTO\", type text}, {\"TELEFONO\", type any}, {\"NPS\", type any}, {\"RESPONSABLE\", type text}, {\"Comentarios\", type text}, {\"A\", Int64.Type}, {\"B\", Int64.Type}, {\"C\", Int64.Type}, {\"D\", Int64.Type}, {\"E\", Int64.Type}, {\"F\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Sector\", each \"NAL\"),",
                "    #\"Appended Query\" = Table.Combine({#\"Added Custom\", NPS_XB, NPS_PHAR, NPS_BBA, NPS_VMODAL}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Appended Query\",{\"Source.Name\", \"Nombre\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"A\", type text}, {\"B\", type text}, {\"C\", type text}, {\"D\", type text}, {\"E\", type text}, {\"F\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type1\",null,\"0\",Replacer.ReplaceValue,{\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"NPS\", type text}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type3\", \"Custom\", each Text.Select([NPS],{\"0\"..\"9\"})),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Custom\", Int64.Type}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Changed Type4\",{{\"A\", Int64.Type}, {\"B\", Int64.Type}, {\"C\", Int64.Type}, {\"D\", Int64.Type}, {\"E\", Int64.Type}, {\"F\", Int64.Type}}),",
                "    #\"Unpivoted Only Selected Columns\" = Table.Unpivot(#\"Changed Type2\", {\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"}, \"Attribute\", \"Value\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Unpivoted Only Selected Columns\",{\"NPS\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns1\",{{\"Custom\", \"NPS\"}}),",
                "    #\"Changed Type5\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"ID REGISTROS\", type text}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type5\",0,1E-05,Replacer.ReplaceValue,{\"NPS\"}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Replaced Value1\", {\"CARRIER\"})",
                "in",
                "    #\"Removed Errors\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NPS_XB",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb4abf89-ba16-4eee-9455-b45bf5997244",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "CARRIER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9e1158c-762f-480a-ae72-11b01fdcc844",
            "sourceColumn": "CARRIER",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "22ad3fcb-64db-4113-b2d5-ec9a89b45b19",
            "sourceColumn": "FECHA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_57bd1f4e-d41f-4c3e-bf40-4b347aeaa27e"
                },
                "isDefault": true,
                "relationship": "a1b65d05-e011-4e3d-8490-4917cea5c8bb"
              }
            ]
          },
          {
            "name": "Nombre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e191b7be-748c-473f-8aab-58085d6d62e2",
            "sourceColumn": "Nombre",
            "summarizeBy": "none"
          },
          {
            "name": "CONTACTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08873109-2055-4968-8a92-b917d865bd13",
            "sourceColumn": "CONTACTO",
            "summarizeBy": "none"
          },
          {
            "name": "TELEFONO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc0c7169-43f0-463c-808a-d37e960bcd4f",
            "sourceColumn": "TELEFONO",
            "summarizeBy": "none"
          },
          {
            "name": "NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "319831f7-fea4-4d7e-950b-16c6420d0f78",
            "sourceColumn": "NPS",
            "summarizeBy": "sum"
          },
          {
            "name": "RESPONSABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da936448-9dfb-46ce-9548-2fa48ed4361f",
            "sourceColumn": "RESPONSABLE",
            "summarizeBy": "none"
          },
          {
            "name": "Comentarios",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f829c75e-2627-4c56-8252-29c90008bd32",
            "sourceColumn": "Comentarios",
            "summarizeBy": "none"
          },
          {
            "name": "A",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9fff552-6194-4e90-8157-9827a1ae31ab",
            "sourceColumn": "A",
            "summarizeBy": "sum"
          },
          {
            "name": "B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dca40d8e-5027-4138-823c-c70785b29fe9",
            "sourceColumn": "B",
            "summarizeBy": "sum"
          },
          {
            "name": "C",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d06e957c-386b-43ff-ba19-0212771b550c",
            "sourceColumn": "C",
            "summarizeBy": "sum"
          },
          {
            "name": "D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a72a3bf4-9ba8-44a0-90f1-c0f622c536a6",
            "sourceColumn": "D",
            "summarizeBy": "sum"
          },
          {
            "name": "E",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b92f8ba3-139a-4fb2-90e8-43065aa374f7",
            "sourceColumn": "E",
            "summarizeBy": "none"
          },
          {
            "name": "F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b486d94-4c80-41b3-90f1-e46629cf9ade",
            "sourceColumn": "F",
            "summarizeBy": "sum"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9cd71bc-651a-4274-a67d-6b79f934014d",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "ID REGISTROS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96794f0c-6f8f-431f-ba65-edb4e06aecc4",
            "sourceColumn": "ID REGISTROS",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34c5f78e-6361-4d38-a336-25bd1c741b54",
            "sourceColumn": "Periodo",
            "summarizeBy": "none"
          },
          {
            "name": "G",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4d02cd4-dcc7-449f-8e34-a37dc726cd48",
            "sourceColumn": "G",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e627f060-c457-4a3c-8d0b-8624db68bf67",
        "partitions": [
          {
            "name": "NPS_XB-c24882bf-74a2-4bb9-b112-81dae2b0aead",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (2)\", each #\"Transform File (2)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (2)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample File (2)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"CARRIER\", type text}, {\"FECHA\", type date}, {\"Nombre\", type text}, {\"CONTACTO\", type text}, {\"TELEFONO\", type any}, {\"NPS\", Int64.Type}, {\"RESPONSABLE\", type text}, {\"Comentarios\", type text}, {\"A\", Int64.Type}, {\"B\", Int64.Type}, {\"C\", Int64.Type}, {\"D\", Int64.Type}, {\"E\", type any}, {\"F\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Sector\", each \"XB\")",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_57bd1f4e-d41f-4c3e-bf40-4b347aeaa27e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5a7d796d-044b-4348-a613-e886f1be7ca5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5c72ae2c-561c-42f9-bb40-605de14a9333",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "05b9998a-33d1-4211-ba97-0254071f9eba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0270679a-7672-4084-9ca2-89d87dbefefc",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6c606c10-4311-4100-94dd-1d313b0e8a25",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2c66fdac-0b14-41e9-b521-b1c155ff3fb7",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "87806162-df08-4397-9e7f-8127b235004f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "4c3f3a20-8b5d-43ca-9916-c91dca934c86",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "4761d9f0-095b-4f86-bd7b-b090ae53ca3e",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "a028030f-031b-480d-a32b-90ef5c76a42c",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "2c7b8d0a-aca1-47bc-a16d-df45cb5fe021",
                "ordinal": 3
              }
            ],
            "lineageTag": "57b0e792-55d8-4857-a5db-ca52d5328ea5"
          }
        ],
        "isHidden": true,
        "lineageTag": "387ee887-1f1f-4123-9377-86f7f0b6a0c1",
        "partitions": [
          {
            "name": "LocalDateTable_57bd1f4e-d41f-4c3e-bf40-4b347aeaa27e-bd4b15a5-c821-404b-bd9a-fe818ebbeccc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('NPS_XB'[FECHA])), 1, 1), Date(Year(MAX('NPS_XB'[FECHA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "CATEGORIAS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Columna1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e64eecc-a4fe-4901-93fc-92da7fdb6e9f",
            "sourceColumn": "Columna1",
            "summarizeBy": "none"
          },
          {
            "name": "Categorias ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a89e3aa-937b-42e1-927a-b1426dc4fc24",
            "sourceColumn": "Categorias ",
            "summarizeBy": "none"
          },
          {
            "name": "Totales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75e0f27d-3a72-4214-81f1-f2ae42f6e0d2",
            "sourceColumn": "Totales",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "534868d6-dd09-4c5d-849b-66db17da91cb",
        "partitions": [
          {
            "name": "CATEGORIAS-b8fbe010-101e-4058-9d2e-da55717119a8",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\\Master Visita de Carriers 2023 - Q1.xlsx\"), null, true),",
                "    CATEGORIAS_Table = Source{[Item=\"CATEGORIAS\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(CATEGORIAS_Table,{{\"Columna1\", type text}, {\"Categorias \", type text}, {\"Totales\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas NPS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "152638df-744e-42a6-ab3c-5501a66ccb4c",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4e53cd09-dbfa-4e35-9c9c-151e1e6f044b",
        "measures": [
          {
            "name": "PromedioNPS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(NPS_NACIONAL[NPS])",
            "lineageTag": "7b53d471-2e9d-4db4-b8d8-b823fcd45bf9"
          },
          {
            "name": "ClasificaciónNPS",
            "expression": [
              "SWITCH(TRUE(),",
              "              [PromedioNPS]=BLANK(),\"Sin Respuesta\",",
              "              [PromedioNPS]<8,\"Detractor\",",
              "              [PromedioNPS]>8,\"Promotor\",\"Neutro\")"
            ],
            "lineageTag": "ebff4ef4-7640-4742-aa1b-89214d32d34b"
          },
          {
            "name": "Promotores",
            "expression": "CALCULATE(DISTINCTCOUNT(NPS_NACIONAL[ID REGISTROS]),NPS_NACIONAL[ClasificaciónNPS]=\"Promotor\")+0",
            "formatString": "0",
            "lineageTag": "c1037e19-33f7-4798-bb84-381e2b42084a"
          },
          {
            "name": "Detractores",
            "expression": "CALCULATE(DISTINCTCOUNT(NPS_NACIONAL[ID REGISTROS]),NPS_NACIONAL[ClasificaciónNPS]=\"Detractor\")+0",
            "formatString": "0",
            "lineageTag": "ead41c52-280c-489f-b0b1-ea926b83a41e"
          },
          {
            "name": "Neutros",
            "expression": "CALCULATE(DISTINCTCOUNT(NPS_NACIONAL[ID REGISTROS]),NPS_NACIONAL[ClasificaciónNPS]=\"Neutro\")+0",
            "formatString": "0",
            "lineageTag": "0d54433b-26ea-46b2-8a3a-139603efd4d0"
          },
          {
            "name": "Sin Respuesta",
            "expression": "CALCULATE(DISTINCTCOUNT(NPS_NACIONAL[ID REGISTROS]),NPS_NACIONAL[ClasificaciónNPS]=\"Sin Respuesta\")+0",
            "formatString": "0",
            "lineageTag": "2bc5418c-b554-43ac-86a5-17a2b748edf8"
          },
          {
            "name": "NPS",
            "expression": "(DIVIDE(([Promotores]-[Detractores]),([Registros Totales]-[Sin Respuesta])))*100",
            "formatString": "0.00",
            "lineageTag": "4223c119-0f88-4d3e-8d9b-5c2a11d960c4"
          },
          {
            "name": "Registros Totales",
            "expression": "DISTINCTCOUNT(NPS_NACIONAL[ID REGISTROS])",
            "formatString": "0",
            "lineageTag": "955d30de-27b3-48ff-8557-62869b1e86bc"
          },
          {
            "name": "Objetivo NPS",
            "expression": [
              "SWITCH(TRUE(),",
              "                  SELECTEDVALUE(calendarconection[Quarter])=1 && SELECTEDVALUE(calendarconection[Year])=2023,60,",
              "                  SELECTEDVALUE(calendarconection[Quarter])=2 && SELECTEDVALUE(calendarconection[Year])=2023,65,",
              "                  SELECTEDVALUE(calendarconection[Quarter])=3 && SELECTEDVALUE(calendarconection[Year])=2023,75,",
              "                  SELECTEDVALUE(calendarconection[Quarter])=4 && SELECTEDVALUE(calendarconection[Year])=2023,80",
              "                  )"
            ],
            "formatString": "0",
            "lineageTag": "d69f1ab3-18b5-4500-a519-3a17ffa596bf"
          },
          {
            "name": "CumplimientoNPS",
            "expression": "DIVIDE('Medidas NPS'[NPS],[Objetivo NPS])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "3c51f0f5-c408-4b1b-a12f-7f7b567830b5"
          },
          {
            "name": "Calificacion NPS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "IF([CumplimientoNPS]>1.20,120,[CumplimientoNPS]*100)",
            "formatString": "0",
            "lineageTag": "24d89059-9fed-4ff1-825c-087bcd8de65e"
          },
          {
            "name": "TITULOS NPS",
            "expression": "SWITCH(TRUE(), 'Medidas NPS'[NPS]>=70,\"EXCELLENT\",'Medidas NPS'[NPS]<70 && 'Medidas NPS'[NPS]>=30, \"GREAT\",'Medidas NPS'[NPS]<30 && 'Medidas NPS'[NPS]>=1,\"GOOD\",'Medidas NPS'[NPS]<1,\"???\" )",
            "lineageTag": "f4e55343-2589-4736-a632-e410daa470d2"
          }
        ],
        "partitions": [
          {
            "name": "Medidas NPS-c6bf6082-eec6-4ee6-987c-fd5c6959754d",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "PROJECTSUNICOS",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "565925b430404a7f9fb6e333a9ce8a7a"
          }
        ],
        "columns": [
          {
            "name": "UNICO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b0a59c2b-540a-4467-bcee-748d77cc3eec",
            "sourceColumn": "LaneSpot1[UNICO]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e435750c-aac8-4da0-9405-3d9c7c9e22a2",
        "partitions": [
          {
            "name": "PROJECTSUNICOS-13a64456-c007-4351-af56-1e0bd00a07c7",
            "mode": "import",
            "source": {
              "expression": "VALUES(LaneSpot1[UNICO])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calendarconnection_Alternative",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b6d8c8aa214943f5ae5dc4561e2cc05b"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "94f36d71-6bb5-4ff3-a18f-67fa6b9e4b49",
            "sourceColumn": "calendarconection[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_464403aa-219d-4a77-8110-84719da5ddfb"
                },
                "isDefault": true,
                "relationship": "fa424948-e3eb-4a32-b1bb-81d1a83f5b2e"
              }
            ]
          },
          {
            "name": "Monthname",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7c557e31-cd32-4ef7-8e5b-7402ac446487",
            "sortByColumn": "Month",
            "sourceColumn": "calendarconection[Monthname]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ac7b87cd-a900-42fd-8b9c-edbec76403ed",
            "sourceColumn": "calendarconection[Month]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1869937e-3f84-4d90-98d1-f642f82a0291",
            "sourceColumn": "calendarconection[Quarter]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "15fcb46d-4444-446b-9592-6c54e1bb3e41",
            "sourceColumn": "calendarconection[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8d0446d1-b741-44ae-b514-90a5c2236666",
            "sourceColumn": "calendarconection[Week]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2c6d484a-bd5a-451d-b9d0-0bce5d330266",
            "sourceColumn": "calendarconection[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Column 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2a9be502-00f0-4617-a80a-87ef9ba7ff16",
            "sourceColumn": "calendarconection[Column 2]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "670330fe-390e-44b8-bd74-96ef83e62427",
            "sourceColumn": "calendarconection[Week2]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Anio-Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "19732990-e81e-44e8-9934-6c28697eb8ef",
            "sourceColumn": "calendarconection[Anio-Semana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "RankAnio-Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f7438cad-c2ee-4245-9149-83ccdf2b74e0",
            "sourceColumn": "calendarconection[RankAnio-Semana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "29semanasContempladas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a0ad6efd-76b0-47d5-b8e5-79fed11e3797",
            "sourceColumn": "calendarconection[29semanasContempladas]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ef88b5a0-ecad-4332-914d-744287375caf",
            "sourceColumn": "calendarconection[Year-Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "02c6e01c-b91d-40ab-b9cf-d4d0531561a0",
        "partitions": [
          {
            "name": "Calendarconnection_Alternative-3bebaa73-240a-46f0-a05d-4909e983c7ed",
            "mode": "import",
            "source": {
              "expression": "calendarconection",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "94a38ee872c24a4085b1b4f923b215ae"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "f92ef569-cb94-4e66-841f-f5efe3554dc0",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "39034774-363f-4810-b999-ed975064f0c4",
        "measures": [
          {
            "name": "MonthRange",
            "expression": "SELECTEDVALUE('Parameter'[Parameter])",
            "formatString": "0",
            "lineageTag": "0cfab528-4685-4ff7-a482-957b36f54ed4"
          }
        ],
        "partitions": [
          {
            "name": "Parameter-27a78d06-b704-4360-9d08-fb6459e0d87a",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 20, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "TotalDayBand",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5ed599f56d91453da4e4abd236cb38f8"
          }
        ],
        "columns": [
          {
            "name": "Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "49a09899-6c47-4300-8cae-c0a33ec03478",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c30c412c-bf5c-455d-ac28-f870d396b6ea",
        "partitions": [
          {
            "name": "TotalDayBand-8541dcee-ca51-4523-8f62-7a9c71807584",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0,1000,1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Band Size",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0f6b10e76bc34acca5f9b638b2d3528d"
          }
        ],
        "columns": [
          {
            "name": "Band Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4f133b6b-4b06-4a0c-a628-075b5c1c5361",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a5a44f7e-3b98-4dee-a0c1-475c2a5ad544",
        "measures": [
          {
            "name": "Band Size Value",
            "expression": "SELECTEDVALUE('Band Size'[Band Size], 1)",
            "formatString": "0",
            "lineageTag": "b28c0d35-9252-42c9-94c8-349379308e29"
          },
          {
            "name": "SelectedBandSize",
            "expression": "SELECTEDVALUE('Band Size'[Band Size],1)",
            "formatString": "0",
            "lineageTag": "804b219c-8c5f-4479-9746-c60a1d088578"
          },
          {
            "name": "MinDay from bandsize",
            "expression": "MINX(ALL(TotalDayBand),TotalDayBand[Days])",
            "formatString": "0",
            "lineageTag": "0a975eb0-8122-459c-8ada-db9343d4b1d6"
          },
          {
            "name": "MaxDay from bandsize",
            "expression": "MAXX(ALL(TotalDayBand),TotalDayBand[Days])",
            "formatString": "0",
            "lineageTag": "b9693467-1412-4f88-a06e-1d0e515c2f0d"
          },
          {
            "name": "CountofCarriers in each Band",
            "expression": [
              "",
              "VAR  _minValue = [MinDay from bandsize]",
              "VAR  _maxValue = [MaxDay from bandsize]",
              "VAR  _bandsize = [SelectedBandSize]",
              "VAR  _DayBandTable = GENERATESERIES(_minValue,_maxValue,_bandsize)",
              "VAR  _currDay = SELECTEDVALUE(TotalDayBand[Days])",
              "VAR  _bandhead = MAXX(",
              "                    FILTER( _DayBandTable,",
              "                    [Value]<=_currDay),[Value])",
              "VAR _bandtail = _bandhead + _bandsize",
              "RETURN ",
              "IF(_currDay = _bandhead,",
              "     CALCULATE( ",
              "                COUNTROWS(DISTINCT('Carrier Care (2)'[Proveedor/Nombre Comercial])),",
              "                TotalDayBand[Days]>=_bandhead && TotalDayBand[Days]<_bandtail",
              "                )",
              "                )",
              "",
              "              ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ae7ad4da-b43a-43d2-87e9-a68b281557dd"
          },
          {
            "name": "Months to show_Histogram",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [CountofCarriers in each Band],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              "",
              "",
              "                                "
            ],
            "formatString": "0",
            "lineageTag": "ee054e94-fb99-445f-bb1f-5fe477fd665a"
          },
          {
            "name": "Months to show_ Distribution",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DistributionDiasRCT]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              "",
              "",
              "                                "
            ],
            "lineageTag": "7fbeb546-6adb-49e0-b165-df7b6917080a"
          },
          {
            "name": "Months to show_Mean",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [Mean (μ)],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f601ac06-f6d6-48f6-b5f2-8565ec7dfd15"
          },
          {
            "name": "Months to show_σ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [Standard.Dev (σ)],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "324b9910-b0a6-4900-8bcc-228d924d9a48"
          },
          {
            "name": "Months to show_X+3σ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [X+3σ],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "8adbd0fe-b2e8-4948-8bc3-4367537e8620"
          },
          {
            "name": "Months to show_X-3σ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [X-3σ],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "769b33a5-a33a-4da7-a98b-ac879603a4dd"
          },
          {
            "name": "Months to show_X+1σ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [X+1σ],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "109eadef-f25b-4cfd-8644-5b5b1c3314a8"
          },
          {
            "name": "Months to show_X-1σ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [X-1σ],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "5a664dff-560a-4693-8d81-4dc88c85d38d"
          },
          {
            "name": "Months to show_DistributionRCTmeasure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR X_value = GENERATESERIES(INT([Months to show_X-3σ]),INT([Months to show_X+3σ]),1)",
              "                         VAR _Xselected = SELECTEDVALUE(NormalDistribution[X])",
              "                         VAR NormalDistribution_1 = NORM.DIST(MAXX(FILTER( X_value,",
              "                    [Value]=_Xselected),[Value]),[Months to show_Mean],[Months to show_σ],FALSE)",
              "                         VAR seleccion = IF(MAXX(FILTER( X_value,",
              "                    [Value]=_Xselected),[Value])<_Xselected || MAXX(FILTER( X_value,",
              "                    [Value]=_Xselected),[Value])>_Xselected,BLANK(),NormalDistribution_1)",
              "                         return",
              "                         seleccion"
            ],
            "lineageTag": "7f4e86dd-4785-4363-9c6b-5689dbb524de"
          },
          {
            "name": "Months to show_ProbabilityAreaSelected",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR Cond_1 = ",
              "                   CALCULATE([Average_X],",
              "                       KEEPFILTERS(",
              "                           FILTER(",
              "                               ALL(NormalDistribution),NormalDistribution[X]<=[Mean Value])",
              "                               )",
              "                            )",
              "                        ",
              "             VAR seleccion_1 = IF(Cond_1=BLANK(),BLANK(),[Months to show_DistributionRCTmeasure])",
              "             VAR Cond_2 = ",
              "                   CALCULATE([Average_X],",
              "                       KEEPFILTERS(",
              "                           FILTER(",
              "                               ALL(NormalDistribution),NormalDistribution[X]>=[Mean Value])",
              "                               )",
              "                            )",
              "                        ",
              "             VAR seleccion_2 = IF(Cond_2=BLANK(),BLANK(),[Months to show_DistributionRCTmeasure])",
              "             ",
              "            RETURN ",
              "            ",
              "                   IF(HASONEVALUE('Probabilty Interval'[Probability]),",
              "                             SWITCH(VALUES('Probabilty Interval'[Index]),",
              "                             2,seleccion_1,",
              "                             1,seleccion_2",
              "                                ),seleccion_1)"
            ],
            "lineageTag": "5da42891-f83e-46f3-b1db-c9ade95677c1"
          },
          {
            "name": "Months to show_μ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR X_valuesolo= ",
              "                   CALCULATE([Average_X],",
              "                       KEEPFILTERS(",
              "                           FILTER(",
              "                               ALL(NormalDistribution),NormalDistribution[X]=FLOOR([Months to show_Mean],1)",
              "                               )",
              "                            )",
              "                        )",
              "             VAR seleccion = IF(X_valuesolo=BLANK(),BLANK(),[Months to show_DistributionRCTmeasure])",
              "            RETURN ",
              "            seleccion"
            ],
            "lineageTag": "283e9fe1-18c2-44c8-bf10-19879bcfa128"
          },
          {
            "name": "Months to show_μ-1σ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR X_valuesolo= ",
              "                   CALCULATE([Average_X],",
              "                       KEEPFILTERS(",
              "                           FILTER(",
              "                               ALL(NormalDistribution),NormalDistribution[X]=FLOOR([Months to show_X-1σ],1)",
              "                               )",
              "                            )",
              "                        )",
              "             VAR seleccion = IF(X_valuesolo=BLANK(),BLANK(),[Months to show_DistributionRCTmeasure])",
              "            RETURN ",
              "            seleccion"
            ],
            "lineageTag": "2e4ea834-fc31-4423-8d12-3b6ef5ee287b"
          },
          {
            "name": "Months to show_μ+1σ",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR X_valuesolo= ",
              "                   CALCULATE([Average_X],",
              "                       KEEPFILTERS(",
              "                           FILTER(",
              "                               ALL(NormalDistribution),NormalDistribution[X]=FLOOR([Months to show_X+1σ],1)",
              "                               )",
              "                            )",
              "                        )",
              "             VAR seleccion = IF(X_valuesolo=BLANK(),BLANK(),[Months to show_DistributionRCTmeasure])",
              "            RETURN ",
              "            seleccion"
            ],
            "lineageTag": "e246ce70-5c9f-4629-9502-5d3a7e9e5275"
          },
          {
            "name": "Months to show_Z",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR X_values = GENERATESERIES(INT([Months to show_X-3σ]),INT([Months to show_X+3σ]),1)",
              "                         VAR _Xselected = SELECTEDVALUE(NormalDistribution[X])",
              "                         VAR X_value = MAXX(FILTER( X_values,",
              "                    [Value]=_Xselected),[Value])",
              "                         VAR Z_value = (X_value-[Months to show_Mean])/[Months to show_σ]",
              "                         VAR seleccion = IF(MAXX(FILTER( X_values,",
              "                    [Value]=_Xselected),[Value])<_Xselected || MAXX(FILTER( X_values,",
              "                    [Value]=_Xselected),[Value])>_Xselected,BLANK(),Z_value)",
              "                         return",
              "                        seleccion",
              "     "
            ],
            "lineageTag": "1fb2103e-b4f5-4abf-a510-b92ab3d94abb"
          },
          {
            "name": "Months to show_Normal Z value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "ROUND(CALCULATE( [Months to show_Z], FILTER(ALL(NormalDistribution),NormalDistribution[X]=[Mean Value])),2)",
              "                 "
            ],
            "lineageTag": "a03bd329-82fd-495c-a30f-7063dd2ac66a"
          },
          {
            "name": "Months to show_ProbabilityArea by Z",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR if_positive = CALCULATE([ProbabilityArea],FILTER(ALL(FrequencyDistribution),FrequencyDistribution[X value]= [Months to show_Normal Z value]))",
              "                       VAR if_negative = 1-CALCULATE([ProbabilityArea],FILTER(ALL(FrequencyDistribution),FrequencyDistribution[X value]= ABS([Months to show_Normal Z value])))",
              "                       VAR seleccion = IF([Months to show_Normal Z value]>0,if_positive,if_negative)",
              "                       RETURN",
              "                       seleccion"
            ],
            "lineageTag": "6d8c7a00-0b1a-48a8-8356-9ea99c9b681e"
          },
          {
            "name": "Months to show_Real Probability",
            "expression": [
              "IF(HASONEVALUE('Probabilty Interval'[Probability]),",
              "                       SWITCH(VALUES('Probabilty Interval'[Index]), ",
              "                                                  2,[Months to show_ProbabilityArea by Z],",
              "                                                  1,1-[Months to show_ProbabilityArea by Z]),",
              "                                                  [Months to show_ProbabilityArea by Z])"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "0bc5a046-7f7d-4e31-bd83-2e16e8bc85e0"
          },
          {
            "name": "Months to show_Carriers",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( SELECTEDVALUE('Carrier Care (2)'[Proveedor/Nombre Comercial]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "lineageTag": "300a6fa1-0728-4a86-a349-b57494242d6c"
          },
          {
            "name": "Months to show_CCarriers",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( COUNTROWS(DISTINCT('Carrier Care (2)'[Proveedor/Nombre Comercial])),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "formatString": "0",
            "lineageTag": "fc570dd7-bd7b-491f-b6a8-c40f6b8eba1e"
          },
          {
            "name": "Months to show_DiasDocs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [DIAS DOCS],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "6ffc4203-6f0a-4ebe-8e1e-ae5055bc7d9f"
          },
          {
            "name": "Months to show_DiasBlack",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [DIAS BLACK TRUST],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "97a4e284-0892-4053-8032-ff6fe8653734"
          },
          {
            "name": "Months to show_DiasSAP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [DIAS SAP],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "029da149-390c-477b-bb1c-72f5c1f825a5"
          },
          {
            "name": "Months to show_DiasSP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [DIAS SEGURIDAD],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "72c5ebc0-de2a-43b3-a272-4b55a773a5a9"
          },
          {
            "name": "Months to show_DiasLearning",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [DIAS LEARNING],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1538abe9-1225-4643-8807-9dbed9b73ee9"
          },
          {
            "name": "Months to show_AvanceGeneral",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[% de Avance General]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "bc43921f-9471-4c47-81d8-4d30aa21598e"
          },
          {
            "name": "Dias Anticipados (Fin RC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADO FIN RCT]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "9bf0b7c8-e387-454e-99dd-eb6f323fe4ab"
          },
          {
            "name": "Dias Fuera de tiempo (Fin RC)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS fuera de tiempo FIN RCT]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "lineageTag": "d53aa50c-9ca4-42f4-9247-743191de9868"
          },
          {
            "name": "Dias Anticipados (Inicio BT)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS DE INICIO BLACK]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "0f08c903-ae5e-4c76-9562-1bc60f6e1b58"
          },
          {
            "name": "Dias Anticipados (Inicio SAP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS DE INICIO SAP]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "663659fc-cb08-46a7-a7d6-fb5923b39671"
          },
          {
            "name": "Dias Anticipados (Inicio SP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS DE INICIO SP]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "b6a5f86e-393a-4c58-94cc-76baf45f5ae5"
          },
          {
            "name": "Dias Anticipados (Inicio Learning)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS DE INICIO LEARNING]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "6691bf26-a4d8-481f-99d7-8175eb31e9dc"
          },
          {
            "name": "Dias Anticipados (Fin BT)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS FIN BLACK]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "a70a712a-ca49-4e5a-9064-eeb0f71b4dda"
          },
          {
            "name": "Dias Anticipados (Fin SAP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS FIN SAP]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "f992488c-c165-417d-ab0d-bc1c7907d470"
          },
          {
            "name": "Dias Anticipados (Fin SP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS FIN SP]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "b3c0a300-5a53-487d-9835-7db8ba7d03a1"
          },
          {
            "name": "Dias Anticipados (Fin Learning)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADOS FIN LEARNING]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "92afc20a-0328-4e34-91ab-0390a031b836"
          },
          {
            "name": "Dias Anticipados (Fin Docs)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS ANTICIPADO TIEMPO DOCS]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT*-1"
            ],
            "lineageTag": "fbab4755-1e25-4c72-a4e0-3febd345d828"
          },
          {
            "name": "Dias Fuera de tiempo (Fin Docs)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS FUERA DE TIEMPO DOCS]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "lineageTag": "8362ab1a-bad2-407a-97cf-fb9376df8687"
          },
          {
            "name": "Dias Fuera de tiempo (Fin BT)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS FUERA DE TIEMPO FIN BLACK]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "lineageTag": "fa691d87-988d-497e-9670-e1b39f3b9418"
          },
          {
            "name": "Dias Fuera de tiempo (Fin SAP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS FUERA DE TIEMPO FIN SAP]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "lineageTag": "65610b55-4838-46dc-9980-b232aba4c91e"
          },
          {
            "name": "Dias Fuera de tiempo (Fin SP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS FUERA DE TIEMPO FIN SP]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "lineageTag": "8482cf80-71f5-4344-864f-21bd74e11774"
          },
          {
            "name": "Dias Fuera de tiempo (Fin LEARNING)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( AVERAGE('Carrier Care (2)'[DIAS FUERA DE TIEMPO FIN LEARNING]),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "lineageTag": "237d72b3-bfc7-43c1-8900-cf0f3ed162bd"
          },
          {
            "name": "Months to show_AvanceLearning",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [AvanceLearning],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "f1b4b0b6-a588-4913-a86c-e8e7399e049f"
          },
          {
            "name": "MaxLearningDays_Carrier",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(MAXX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),[Months to show_DiasLearning]),FILTER(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),[Months to show_AvanceLearning]=0.2))",
            "formatString": "0",
            "lineageTag": "93ab2b92-33e8-4ba8-be4c-ccd86a5d4605"
          },
          {
            "name": "MaxCarrier_Name",
            "expression": [
              "VAR M_1=IF([MaxLearningDays_Carrier]=[Months to show_DiasLearning],1,0)",
              "                  VAR M_2=IF(M_1=1,[Months to show_Carriers],BLANK())",
              "                  RETURN",
              "                  M_1"
            ],
            "formatString": "0",
            "lineageTag": "638f5f9a-44dd-474a-991b-ed2633d5afa6"
          },
          {
            "name": "MinCarrier_Name",
            "expression": [
              "VAR M_1=IF([MinLearningDays_Carrier]=[Months to show_DiasLearning],1,2)",
              "                  VAR M_2=IF(M_1=1,[Months to show_Carriers],BLANK())",
              "                  RETURN",
              "                  M_1"
            ],
            "formatString": "0",
            "lineageTag": "f6fa744b-f198-4b75-85ea-9a5dcb245bfb"
          },
          {
            "name": "MinLearningDays_Carrier",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(MINX(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),[Months to show_DiasLearning]),FILTER(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),[Months to show_AvanceLearning]=0.2))",
            "formatString": "0",
            "lineageTag": "5c100756-1583-4dba-bc14-00622504e473"
          },
          {
            "name": "Learning Completado",
            "expression": "CALCULATE([Months to show_CCarriers],FILTER(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),[Months to show_AvanceLearning]=0.2))",
            "formatString": "0",
            "lineageTag": "36fb67e9-f4ba-4280-bb60-b5dc621832fa"
          },
          {
            "name": "Learning Incompleto",
            "expression": "CALCULATE([Months to show_CCarriers],FILTER(ALLSELECTED('Carrier Care (2)'[Proveedor/Nombre Comercial]),[Months to show_AvanceLearning]<>0.2))",
            "formatString": "0",
            "lineageTag": "b2a0447f-7c35-4400-b488-6b50ecaf00e1"
          },
          {
            "name": "Months to show_AvanceDOCS",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [AvanceDOCS],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "3459406d-1a37-427e-975f-be6261f326ef"
          },
          {
            "name": "Months to show_AvanceBLACKTRUST",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [AvanceBLACKTRUST],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "9a3889cf-9c10-4433-9cf7-ce5aa34f95d8"
          },
          {
            "name": "Months to show_AvanceSAP",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [AvanceSAP],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "0bd50e6b-8ebc-4b55-b68b-8c21232f194f"
          },
          {
            "name": "Months to show_AvanceSP",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [AvanceSP],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "b76a14c8-5b38-4134-8270-76361a60b87d"
          },
          {
            "name": "Months to show_CCarriersScorecard",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( COUNTROWS(DISTINCT(Scorecard[CarrierName])),",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "formatString": "0",
            "lineageTag": "d51329b2-f9d8-4021-9b3e-a382a6b4c8dd"
          },
          {
            "name": "Months to show_pend_cap",
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [Pend_cap],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT"
            ],
            "formatString": "0",
            "lineageTag": "cb9027ed-aa2c-433a-a3a0-164ea8e4633d"
          },
          {
            "name": "Months to show_VIAJES",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "VAR MAX_DATE= MAX(calendarconection[Date])",
              "                   VAR PREVIOUSDATES = DATESINPERIOD(Calendarconnection_Alternative[Date],MAX_DATE,-[MonthRange],MONTH)",
              "                   VAR RESULT = CALCULATE( [Viajes_3],",
              "                                REMOVEFILTERS(calendarconection),",
              "                                KEEPFILTERS(PREVIOUSDATES),",
              "                                USERELATIONSHIP(calendarconection[Date],Calendarconnection_Alternative[Date])",
              "                                )",
              "                              RETURN",
              "                            RESULT",
              ""
            ],
            "lineageTag": "b5671707-6e2a-4209-aebb-9f277d03d058"
          }
        ],
        "partitions": [
          {
            "name": "Band Size-4d4d227e-3427-452a-9ac6-97d1dd73bb3c",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 120, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "NormalDistribution",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "bd734bdb0f8e45659345f0d0382d84d5"
          }
        ],
        "columns": [
          {
            "name": "f(x)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "expression": "NORM.DIST(NormalDistribution[X],[Mean (μ)],[Standard.Dev (σ)],FALSE)",
            "formatString": "0.00000",
            "lineageTag": "b6ff14bd-8a9e-489c-8859-0900b47b8b3e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "X_texto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "NormalDistribution[X]",
            "lineageTag": "097b2229-dbfc-48e2-8477-eb61e75e7516",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "X",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8528f220-4109-401e-abd2-66f291fc2b24",
            "sourceColumn": "[X]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Z",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Z]",
            "lineageTag": "b3f9488b-4abc-4775-a26f-3c29276f798f",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "8c160dd2-6585-490e-957d-f3eba9955c53",
        "measures": [
          {
            "name": "Average_X",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "AVERAGE(NormalDistribution[X])",
            "formatString": "0",
            "lineageTag": "f971fc9b-91a4-4398-a7e8-2c017fe403cc"
          }
        ],
        "partitions": [
          {
            "name": "NormalDistribution-3116f216-5d4f-4251-9753-b885bae88947",
            "mode": "import",
            "source": {
              "expression": [
                "var minvalue = -1000",
                "                     var maxvalue = 1000",
                "                     return ",
                "                     SELECTCOLUMNS(CALENDAR(minvalue,maxvalue),\"X\",INT([Date]))",
                "   "
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DayRange",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cb9c541cadae4b8785429caede965248"
          }
        ],
        "columns": [
          {
            "name": "Mean",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0.00",
            "isNameInferred": false,
            "lineageTag": "eda0ecb7-ca2c-4ca4-a293-a7dcc2f2fc84",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "80f674cc-91b5-4021-9644-2f9529b054f9",
        "measures": [
          {
            "name": "Mean Value",
            "expression": "SELECTEDVALUE('DayRange'[Mean], 1)",
            "formatString": "0.00",
            "lineageTag": "9d2d1a74-c710-4641-a480-d06d2d19a530"
          }
        ],
        "partitions": [
          {
            "name": "DayRange-780f3800-57d9-42eb-ad4f-4a02334744a5",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(FLOOR([X-3σ],1),CEILING([X+3σ],1), 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Desviacion",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "403ce6e0055446308c699f1d551dc41d"
          }
        ],
        "columns": [
          {
            "name": "Desviacion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isNameInferred": false,
            "lineageTag": "f595ddce-27d8-4a37-989a-85322e8d53d7",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f371c5a3-35a7-475d-8e74-ed7a1cda9f54",
        "measures": [
          {
            "name": "Desviacion Value",
            "expression": "SELECTEDVALUE('Desviacion'[Desviacion])",
            "formatString": "0.00",
            "lineageTag": "4106f353-7d0f-4acf-9418-ecfefa247d07"
          }
        ],
        "partitions": [
          {
            "name": "Desviacion-b6237c6e-5c7c-4379-8fe8-f3dc5f41b1a2",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(-1000, 1000, 0.5)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Clasificación NPS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Clasificación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "41bcad91-308e-40a1-a9d6-bcb7bd4bca1f",
            "sortByColumn": "Index",
            "sourceColumn": "Clasificación",
            "summarizeBy": "none"
          },
          {
            "name": "Rango",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7870348b-eb90-41e6-8d9f-c8dc48430d1a",
            "sourceColumn": "Rango",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "11f6709f-f890-4656-bdeb-466a0eb8531a",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "574de711-2c73-4f75-ad18-92ab5c3e4263",
        "partitions": [
          {
            "name": "Clasificación NPS-0d3df4ea-e2d7-49b8-a393-8b85c22b7884",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcvf3d1HSUTLQNTZQitUB8oNcHUOAAjGlBgbGqcYGuuYQcdcIZ1cfH1c/hBxIIhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Clasificación = _t, Rango = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Clasificación\", type text}, {\"Rango\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 1, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NormalDistributionOTA_X",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8aeecda406914271b9e153d3a522f0e0"
          }
        ],
        "columns": [
          {
            "name": "X_OTA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0.00",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8b25dffe-4bb8-4def-bb32-9972f01d7bdc",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "b6a7795a-9ae2-4546-9449-d397d3a5f67a",
        "partitions": [
          {
            "name": "NormalDistributionOTA_X-bf9376dc-f22b-49aa-b2e3-a0a418504f53",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(-1000,1000,1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "my bins",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "288efca6a035418d8092ff059f28f990"
          }
        ],
        "columns": [
          {
            "name": "value1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b2c8f6e9-89ef-448f-8abd-4bcb48c48b05",
            "sourceColumn": "[value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "value2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e31d4d9e-fca3-4add-a1e1-8d50e14f2a18",
            "sourceColumn": "[value2]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "bin from",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IFERROR(IF (",
              "    MOD ( 'my bins'[value2], 'my bins'[value1] ) = 0,",
              "    'my bins'[value2],",
              "    BLANK ()",
              "),BLANK())"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c89d3f31-9e41-4974-a4c8-dcf695e4ec05",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "bin to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "'my bins'[bin from]",
              "    + IF ( ISBLANK ( 'my bins'[bin from] ), BLANK (), 'my bins'[value1] )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2b083c59-739d-430b-98d1-7a02aec2fb81",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "df7968ac-d342-48f0-a211-fd0f6129a40e",
        "partitions": [
          {
            "name": "my bins-fa92d940-3157-4329-9260-4033412af425",
            "mode": "import",
            "source": {
              "expression": [
                "",
                " VAR X_value = SUMMARIZE(Scorecard,Scorecard[CarrierName],\"OTA_FULL\",ROUND(AVERAGE(Scorecard[OTA*100]),0))",
                "VAR series1 =",
                "    SELECTCOLUMNS ( GENERATESERIES ( 0, 100, 1 ), \"value1\", [Value] )",
                "VAR series2 =",
                "    SELECTCOLUMNS (",
                "        GENERATESERIES (",
                "            FLOOR ( MINX ( X_value,[OTA_FULL] ), 1 ),",
                "            CEILING ( MAXX ( X_value,[OTA_FULL] ), 1 ),",
                "            1",
                "        ),",
                "        \"value2\", [Value]",
                "    )",
                "RETURN",
                "    GENERATE ( series1, series2 )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "BandSizeOpEx",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "02086011c6d04c0aba093e4fd913c720"
          }
        ],
        "columns": [
          {
            "name": "BandSizeOpEx",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "da089c63-2b79-4b8c-b8b0-ec2c5fe08294",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c4b0130a-d708-4b80-a109-2b84e2c07232",
        "measures": [
          {
            "name": "BandSizeOpEx Value",
            "expression": "SELECTEDVALUE('BandSizeOpEx'[BandSizeOpEx])",
            "formatString": "0",
            "lineageTag": "d1b3e4cd-4257-4c91-a32f-acb3cde9e89c"
          }
        ],
        "partitions": [
          {
            "name": "BandSizeOpEx-4a7cf6ba-5c02-429a-9071-bc7961db61ad",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 1000, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_464403aa-219d-4a77-8110-84719da5ddfb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ed92f18c-1cd9-4ef9-a077-5534a7b65552",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e3e5125b-be60-4369-94e7-8d784b94ddf6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0973b3ad-0d4c-4acd-abe5-071c31e81f47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "139ac904-3fcb-435a-b87b-79dd0ff66f37",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c105358d-3c54-4555-b8b2-f5482dd391f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3218ecc2-ee33-4844-bdaa-04e68ba866b5",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "869c3d97-6340-4ab0-a2d9-3d1d12f0202d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "635d8e0d-6ff8-4cd6-9910-be444d083931",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "26a3a5d7-7177-4079-8ce9-8a7b033ba2cf",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "69f88c6a-3983-485f-845d-ce49dd30b164",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "fbe46c8e-f50c-4d22-9f45-b444dc087c4a",
                "ordinal": 3
              }
            ],
            "lineageTag": "f57491bd-651d-4452-bbcf-ca351963cbb8"
          }
        ],
        "isHidden": true,
        "lineageTag": "86dde83e-3b90-4308-96e0-40bb5c63c953",
        "partitions": [
          {
            "name": "LocalDateTable_464403aa-219d-4a77-8110-84719da5ddfb-1989e9b5-f6b2-475e-aa64-b81fa70508cd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendarconnection_Alternative'[Date])), 1, 1), Date(Year(MAX('Calendarconnection_Alternative'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "NPS_PHAR",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CARRIER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44d11fcf-7b9d-4dfe-8bdb-2e78e5ed2d75",
            "sourceColumn": "CARRIER",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d26edd4-a922-4b5b-a942-ed43a63e022f",
            "sourceColumn": "Periodo",
            "summarizeBy": "none"
          },
          {
            "name": "ID REGISTROS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2553eeb-2921-492c-b56c-77b8a8001b49",
            "sourceColumn": "ID REGISTROS",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "94ccd09e-16af-4446-8b06-82e7c5a16277",
            "sourceColumn": "FECHA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_673e204d-2ac7-4cff-afd1-28ed577fd8a9"
                },
                "isDefault": true,
                "relationship": "f5510de6-f291-4c14-adef-37da8920fca0"
              }
            ]
          },
          {
            "name": "NOMBRE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cd37217-42ab-4be1-bd29-f16a65506ebf",
            "sourceColumn": "NOMBRE",
            "summarizeBy": "none"
          },
          {
            "name": "CONTACTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc42c3a6-9d47-4848-9910-215b32b739f2",
            "sourceColumn": "CONTACTO",
            "summarizeBy": "none"
          },
          {
            "name": "TELEFONO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1523574-53f1-4b4c-87b1-a8656770f187",
            "sourceColumn": "TELEFONO",
            "summarizeBy": "none"
          },
          {
            "name": "NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fc36c526-92ea-4421-8a1f-71a9bc3e8859",
            "sourceColumn": "NPS",
            "summarizeBy": "sum"
          },
          {
            "name": "RESPONSABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fced1a5-ed58-4c53-afc8-2ea6576353a9",
            "sourceColumn": "RESPONSABLE",
            "summarizeBy": "none"
          },
          {
            "name": "COMENTARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7c5ad52-63e6-4d75-a734-a25bd33da556",
            "sourceColumn": "COMENTARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "Column12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "456b9832-75ab-4e29-8708-7062fb7c1b96",
            "sourceColumn": "Column12",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44039abc-f1a6-4bc9-8408-d211aa2489e8",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "HOMOLOGACIÓN DE COMENTARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72dec22e-3798-4700-b3ea-9908ec38193a",
            "sourceColumn": "HOMOLOGACIÓN DE COMENTARIOS",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e125fad5-8ab9-45d4-a060-3093f00780bf",
        "partitions": [
          {
            "name": "NPS_PHAR",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\\Master Visita de Carriers 2023 - Q1.xlsx\"), null, true),",
                "    #\"Carriers PHAR_Sheet\" = Source{[Item=\"Carriers PHAR\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Carriers PHAR_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CARRIER\", type text}, {\"Periodo\", type text}, {\"ID REGISTROS\", type text}, {\"FECHA\", type date}, {\"NOMBRE\", type text}, {\"CONTACTO\", type text}, {\"TELEFONO\", type any}, {\"NPS\", Int64.Type}, {\"RESPONSABLE\", type text}, {\"COMENTARIOS\", type text}, {\"Column12\", type any}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Sector\", each \"PHARMA\")",
                "in",
                "    #\"Added Custom\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_673e204d-2ac7-4cff-afd1-28ed577fd8a9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cdfdc7df-3293-45f6-b9a7-ee4d051751c4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4f284db1-ac73-40ec-959d-cb0f1a6a2db4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "107daaa7-849a-4a32-9812-326625c9851d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "da901a72-bbc5-41a1-8479-8ade2fa94701",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1853956f-a984-4d2b-8715-d5f5c6dd6072",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "faa374fa-0060-4cc4-8b38-c3065eae88f7",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5dc82a45-efc2-48fc-9607-799214ab1460",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "35e97bf8-9608-401a-932c-a49e2f320d69",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "a14696d0-d849-41a7-a8b7-dd4824bd9c60",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "72485feb-8b48-432f-9edd-6a4486083b5d",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "29e58284-7f07-4021-a86f-3b2c0d913fb1",
                "ordinal": 3
              }
            ],
            "lineageTag": "fa3efeda-3dc6-4d57-957e-14713e6e48ed"
          }
        ],
        "isHidden": true,
        "lineageTag": "99793e55-d7c9-4b88-82b3-1f7b98e0d1fe",
        "partitions": [
          {
            "name": "LocalDateTable_673e204d-2ac7-4cff-afd1-28ed577fd8a9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('NPS_PHAR'[FECHA])), 1, 1), Date(Year(MAX('NPS_PHAR'[FECHA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "NPS_BBA",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CARRIER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5925114a-5e2a-46cd-8c0b-17f75ddc3d03",
            "sourceColumn": "CARRIER",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c17df116-09e2-420c-b7e0-732fb08a6172",
            "sourceColumn": "Periodo",
            "summarizeBy": "none"
          },
          {
            "name": "ID REGISTROS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "480452a3-af91-48ea-b58d-9669d74b6db3",
            "sourceColumn": "ID REGISTROS",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "58c3548f-4be0-4fa0-a604-c8c2501820b3",
            "sourceColumn": "FECHA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_cfa88921-9f1b-4bf9-a5b6-66ab306bacbf"
                },
                "isDefault": true,
                "relationship": "dc07c624-2029-478c-aac2-7b37a171ca5f"
              }
            ]
          },
          {
            "name": "NOMBRE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f34e52f2-35ed-4851-b536-d44a82661cf0",
            "sourceColumn": "NOMBRE",
            "summarizeBy": "none"
          },
          {
            "name": "CONTACTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02045d9d-903f-4641-97e5-f54b18e8d737",
            "sourceColumn": "CONTACTO",
            "summarizeBy": "none"
          },
          {
            "name": "TELEFONO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7002241-6996-4472-8216-e3429f2850e4",
            "sourceColumn": "TELEFONO",
            "summarizeBy": "none"
          },
          {
            "name": "NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c10336d5-5355-4f3c-8979-27c7d79890ce",
            "sourceColumn": "NPS",
            "summarizeBy": "sum"
          },
          {
            "name": "RESPONSABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a007cb5-6f7b-426a-b950-425a2455b9f0",
            "sourceColumn": "RESPONSABLE",
            "summarizeBy": "none"
          },
          {
            "name": "COMENTARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "056bd570-0681-476d-a3f9-7c61ad1d0cbf",
            "sourceColumn": "COMENTARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88583075-1bfa-42bf-91d2-d35072830b8c",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5f96480-9c39-481a-bb9e-19bf0545bd6e",
            "sourceColumn": "Column11",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "73519ce3-e681-4ddf-8524-861cd50ef515",
        "partitions": [
          {
            "name": "NPS_BBA",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\\Master Visita de Carriers 2023 - Q1.xlsx\"), null, true),",
                "    #\"Carriers PHAR_Sheet\" = Source{[Item=\"Carriers BBA\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Carriers PHAR_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CARRIER\", type text}, {\"Periodo\", type text}, {\"ID REGISTROS\", type text}, {\"FECHA\", type date}, {\"NOMBRE\", type text}, {\"CONTACTO\", type text}, {\"TELEFONO\", type any}, {\"NPS\", Int64.Type}, {\"RESPONSABLE\", type text}, {\"COMENTARIOS\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Sector\", each \"BBA\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_cfa88921-9f1b-4bf9-a5b6-66ab306bacbf",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "01dd11b2-cb31-4b20-b0f8-f2d726f10a7e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4a91886e-7547-4980-8a2c-b8e66e7f53b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "2f145e23-93c3-4bea-a777-6c5d3bb1faa3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0968ead4-d93a-41cf-a1d8-31b5f78377cb",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "596cfd04-26e4-4dd4-aa9d-c060b2a7be14",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "4c0791c2-762e-434e-a008-b266f9a483f1",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5c4181c8-a4dd-4e15-9015-6876d904300f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "7488056b-dd04-499b-8ebc-1f42b98839ee",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "706a44e9-fc96-4ea5-a4d9-835d9a2f4360",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "517ed574-1718-4586-be0e-086cc031f9d6",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "48ef01d5-4fb7-4157-acf7-5a202c4c18c2",
                "ordinal": 3
              }
            ],
            "lineageTag": "fbf3f295-3d44-4f33-a056-e945444f492b"
          }
        ],
        "isHidden": true,
        "lineageTag": "32872c90-fb96-4912-969b-7bcb669487dd",
        "partitions": [
          {
            "name": "LocalDateTable_cfa88921-9f1b-4bf9-a5b6-66ab306bacbf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('NPS_BBA'[FECHA])), 1, 1), Date(Year(MAX('NPS_BBA'[FECHA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Sector",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a93d0587-0e40-46ec-88cb-e92b9c35ded0",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "430ad3d2-39bb-4ffd-b046-a04d05ccde12",
        "partitions": [
          {
            "name": "Sector",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WinBSitWJVvJz9AHTAR6OQb6OYKaTE4R294coCfP1dwGpigUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Sector = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Sector\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NPS_VMODAL",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CARRIER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0db454a9-e5f3-46ef-a248-1b4079f33d21",
            "sourceColumn": "CARRIER",
            "summarizeBy": "none"
          },
          {
            "name": "Periodo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5f11fff-105f-4638-8cd5-dd99bcdff4f8",
            "sourceColumn": "Periodo",
            "summarizeBy": "none"
          },
          {
            "name": "ID REGISTROS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "176167b7-c8f0-4d43-8b50-b83c11b68877",
            "sourceColumn": "ID REGISTROS",
            "summarizeBy": "none"
          },
          {
            "name": "FECHA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "36a0d9c7-e4f2-4f8d-8863-3f758bc66c46",
            "sourceColumn": "FECHA",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_12956af6-a2d5-4b44-b5ce-445153b830b1"
                },
                "isDefault": true,
                "relationship": "ec946c5f-e1e3-4a4f-bcaf-56f9646b5f1e"
              }
            ]
          },
          {
            "name": "NOMBRE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "def23287-d37e-4666-922e-b2398441f275",
            "sourceColumn": "NOMBRE",
            "summarizeBy": "none"
          },
          {
            "name": "CONTACTO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f22a43bc-ed38-45f2-ac3f-b6763855bbe9",
            "sourceColumn": "CONTACTO",
            "summarizeBy": "none"
          },
          {
            "name": "TELEFONO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2eae770-8322-461b-8995-77b4f6487040",
            "sourceColumn": "TELEFONO",
            "summarizeBy": "none"
          },
          {
            "name": "NPS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f0f1355-2a21-49a7-a95b-dacc17c63137",
            "sourceColumn": "NPS",
            "summarizeBy": "sum"
          },
          {
            "name": "ESTATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90d85136-18dd-425f-a226-d3d6d54901c6",
            "sourceColumn": "ESTATUS",
            "summarizeBy": "none"
          },
          {
            "name": "RESPONSABLE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "594ab288-c2e1-4219-b240-9e61e87d2c7a",
            "sourceColumn": "RESPONSABLE",
            "summarizeBy": "none"
          },
          {
            "name": "COMENTARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3fa8d98a-6fe3-4593-a133-fbc53c48efa3",
            "sourceColumn": "COMENTARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "HOMOLOGACIÓN DE COMENTARIOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12bc7b05-d556-4174-800b-c648f66a3f30",
            "sourceColumn": "HOMOLOGACIÓN DE COMENTARIOS",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b771c3d-e327-4404-a21a-30e5ff357853",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b72835e9-5802-48b7-bedd-e19925515710",
        "partitions": [
          {
            "name": "NPS_VMODAL",
            "mode": "import",
            "queryGroup": "NPS",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\Eduardo Vargas\\OneDrive - Traxión\\CARRIER CARE\\Carrier Care NAL\\Visitas Carriers 1Q 2023\\MASTER VISITA CARRIERS Q1\\Master Visita de Carriers 2023 - Q1.xlsx\"), null, true),",
                "    #\"Carriers PHAR_Sheet\" = Source{[Item=\"Carriers V Modal\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Carriers PHAR_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\",{{\"PERIODO\", \"Periodo\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"CARRIER\", type text}, {\"Periodo\", type text}, {\"ID REGISTROS\", type text}, {\"FECHA\", type date}, {\"NOMBRE\", type text}, {\"CONTACTO\", type text}, {\"TELEFONO\", type any}, {\"NPS\", Int64.Type}, {\"RESPONSABLE\", type text}, {\"COMENTARIOS\", type text}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type\", \"Sector\", each \"VMODAL\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_12956af6-a2d5-4b44-b5ce-445153b830b1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8255010b-e021-4628-848a-3bdeb732335e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "69eef676-5059-4411-b66f-29a0cb482c81",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "bc211ce0-dba2-46c6-b613-6380b7af5977",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d3a4aa41-b70f-40fb-9588-dc36f978602b",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "bd4e6e4e-48c4-4fda-bb02-24ce113e5efc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim. \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "f571fc29-a836-4f6c-8812-28922310b475",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "fb5fe7db-fe9c-4649-9e67-d198415c2507",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "c6baf658-4002-4949-acdd-e788270cbd00",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "c832b20a-de20-4089-8d31-f4b8a045e651",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "a9b05db8-afc8-49d4-a9eb-616a7fbaa3dc",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "d8ee59ef-2f61-4728-b6fd-4fcc92c5af66",
                "ordinal": 3
              }
            ],
            "lineageTag": "771e3d8e-dde7-42bd-8263-ef2ceea0605f"
          }
        ],
        "isHidden": true,
        "lineageTag": "7ce39154-ef99-4670-bda3-8221102d1d63",
        "partitions": [
          {
            "name": "LocalDateTable_12956af6-a2d5-4b44-b5ce-445153b830b1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('NPS_VMODAL'[FECHA])), 1, 1), Date(Year(MAX('NPS_VMODAL'[FECHA])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}